### ISSUE TITLE
Weirdness with jenkins builds

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#102]
All sorts of weirdness is going on now.

For `osx`:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/31/consoleFull

I see stuff like:
```
from distutils.version import StrictVersion
curr = StrictVersion(platform.mac_ver()[0])
mavericks = StrictVersion('\''10.9'\'')
if not hasattr(curr, '\''version'\''): # not on apple
   sys.exit(1)
if curr >= mavericks:
   sys.exit(0)
else:
   sys.exit(1)
'
+ /Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/envs/_build/bin/python -c 'import platform; import sys
from distutils.version import StrictVersion
curr = StrictVersion(platform.mac_ver()[0])
mavericks = StrictVersion('\''10.9'\'')
if not hasattr(curr, '\''version'\''): # not on apple
   sys.exit(1)
if curr >= mavericks:
   sys.exit(0)
else:
   sys.exit(1)
'
+ echo 'on mavericks or higher'
on mavericks or higher
```
and
```
+ binstar --quiet -t **** upload -u omnia --channel main 'miniconda/conda-bld/*/*.tar.bz2'
Using binstar api site https://api.binstar.org
[BinstarError] file miniconda/conda-bld/*/*.tar.bz2 does not exist 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 162, in main
    raise BinstarError('file %s does not exist' % (filename))
BinstarError: file miniconda/conda-bld/*/*.tar.bz2 does not exist
```

On `linux`, the vagrant box is no longer working:
```
+ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: VirtualBox VM is already running.
+ vagrant ssh --command 'rm -f ~/.condarc && true'
ssh_exchange_identification: Connection closed by remote host
```

**Comment by kyleabeauchamp** [comment]
This is unrelated, but I noticed a strange thing on top:

```
97621  SymDaemon    98.5 
```

This is apparently a known (and possibly fixed) bug in symantic products.  I ran the auto-update, so hopefully the machine will be a bit more responsive after the next reboot.

Obviously this isn't going to fix the jenkins problems, but it might

**Comment by kyleabeauchamp** [comment]
OK, I added a `vagrant halt` before `vagrant up` to force a shutdown and it looks like we're back in business, at least on the linux side:

https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/26/console

**Comment by rmcgibbo** [comment]
@jchodera: 
 1. The first thing you posted is not an issue. That's the expected output of the `build.sh` for jpype1 or pyemma or something
 2. The second issue is because you've single quoted a glob shell expansion. When you write `binstar --quiet -t **** upload -u omnia --channel main 'miniconda/conda-bld/*/*.tar.bz2'
Using binstar api site https://api.binstar.org` in POSIX shell, the single quoting of the `*`s means that they're not expanded, so the argument getting passed to the program contains the literal star character, which as expected does not exist.

**Comment by jchodera** [comment]
>  in POSIX shell, the single quoting of the *s means that they're not expanded, so the argument getting passed to the program contains the literal star character, which as expected does not exist.

There are no quotes in this line in the build scripts:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/configure
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/configure

**Comment by rmcgibbo** [comment]
Wierd. Not sure then.
