### ISSUE TITLE
openmm-6.2-py27_0.tar.bz2 contains some erroneous files

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#104]
If you look in the openmm linux py27 package, there are some erroneous files.
```
$ wget https://binstar.org/omnia/openmm/6.2/download/linux-64/openmm-6.2-py27_0.tar.bz2
$ tar -tjvf openmm-6.2-py27_0.tar.bz2
```

In `lib/python2.7/site-packages/`, there's a full copy of `sphinx` and `sphinxcontrib-bibtex`. I don't think this is terrible, but it's not what we want.

**Comment by rmcgibbo** [comment]
Also the case with the osx packages.

**Comment by kyleabeauchamp** [comment]
OK, it's also happening in my manual builds, so it's gotta build our build script?

**Comment by rmcgibbo** [comment]
Yeah. I will look into it. It makes sense how they'd get there, from being installed through the `build: requires`, but it's not obvious to me what we're doing wrong. I looked at the files in the msmbuilder  and mdtraj packages, and there's nothing extra there, even though they obviously have `build: requires` sections.

**Comment by rmcgibbo** [comment]
Ohh. I know what it is.

**Comment by rmcgibbo** [comment]
Well, maybe. Will fix soon.
