### ISSUE TITLE
What should we do with travis after_success scripts that push to binstar?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#110]
I just realized we still have a number of live `after_success.sh` scripts run by travis-ci with lines like this:
```
if [[ "2.7 3.3 3.4" =~ "$python" ]]; then                                                                                                                                           
    conda install --yes binstar                                                                                                                                                     
    binstar -t $BINSTAR_TOKEN upload --force -u omnia -p openmmtools $HOME/miniconda/conda-bld/linux-64/${PACKAGENAME}-*                                                            
fi                                                                                                                                                                                  
```
We presumably do *not* want to keep these active, since they might overwrite our released packages.

What should we do instead, considering the issues we've had with pushing to a different channel overwriting packages in the `main` channel?  Should we have a separate `omnia-dev` org?

**Comment by rmcgibbo** [comment]
For MDTraj, there is a separate package name on binstar called `mdtraj-dev`, but I could get rid of it. What are the current situations in which we actually need the `-dev` binaries? It was mostly for testing, right? IMO, the best outcome would just be to get rid of these `-dev` packages on binstar completely, but I don't know if that's currently possible.

**Comment by mpharrigan** [comment]
+1 get to a point where we don't need dev binaries

**Comment by jchodera** [comment]
We're always going to need to deploy in-development versions to various
environments for testing new features on different machines/environments or
with various collaborators where installing from the github repo is much
more complex than conda installs.

Frequently, features are added to OpenMM that we can make use of
immediately in new features in our downstream packages. We need a way
to.easily build and test, which requires installing development versions of
upstream packages and the current package under development.

If package version releases were very frequent---every few days---there
would be no need for dev packages. But given some packages like OpenMM have
rather infrequent releases, I don't see us being able to ditch dev packages
anytime soon.

**Comment by jchodera** [comment]
I'm going to suggest we push to an omnia-dev org with the git hash (or
truncation) as a version string. Does this sound reasonable to folks?

**Comment by rmcgibbo** [comment]
I would prefer using `openmm-dev` or `yank-dev` package names, in the same omnia repo, over using the "opemm"/"yank" package names in a `omnia-dev` repo. I usually just set the channels in my condarc and forget about them, whereas the package name is much more visible.

**Comment by rmcgibbo** [comment]
Also, you'll need to experiment with the git hash as the version string. Off the top of my head,  it's not clear if `conda install` is going to be able to successfully compare the version strings if they're just sha1 hashes, in order to figure out which one is more recent (and know which to install when you do `conda install openmm-dev`).

**Comment by jchodera** [comment]
That can certainly work.

Any opinions on version strings?

**Comment by rmcgibbo** [comment]
Whatever works. The mdtraj-dev current just uses "dev" for the version number, or maybe `<last-prior-release's-version-number+1>.dev`. If every git-commit gets built by travis and pushed to binstar with a separate version string, you might end up with thousands of "unique" development snapshot `.tar.bz2` files on binstar, which sounds like a mess.
