### ISSUE TITLE
Which Python versions should we support?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#119]
Currently, I think it's 
* python 2.7
* python 3.3
* python 3.4

Is 3.3 necessary?

**Comment by rmcgibbo** [comment]
numpy has os-x wheels on pypi for 27, 33, 34 (https://pypi.python.org/pypi/numpy). on the continuum default channels, packages come out for 26, 27, 33, and 34 (`conda search scikit-learn | grep 0.15.2`). From the download numbers on numpy (`vanity numpy==1.9.1`), it looks like py34 is more popular than py33, but I don't see any reason to remove it from our `omnia-md/conda-recipes`, given that it's already working.

**Comment by mpharrigan** [comment]
The differences between 33 and 34 are small, so supporting it should be easy
