### ISSUE TITLE
conda chooses privious pyemma version as maximum

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#124]
version 1.0a3 is weighted higher by conda than 1.0 or 1.0.1. As a workaround I would suggest deleting the old versions from binstar. Otherwise users are dragging in old versions.

**Comment by jchodera** [comment]
Done.  I've removed everything older than 1.0.1, just in case.

**Comment by marscher** [comment]
Thank you for removing the old stuff!
