### ISSUE TITLE
Enable travis-ci to test recipes by trying to build all of them (but not upload to binstar)

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#13]
We can test all of these recipes now using a scheme similar to that @rmcgibbo and @kyleabeauchamp worked out for `mdtraj`, `repex`, `yank`, and `openmm` by having travis-ci attempt to `conda build packagename; conda install packagename` for each package.

Later, we can also have it build and test an `omnia` package.

**Comment by kyleabeauchamp** [comment]
I think we currently have a good scheme for this that does a mock-build of everything upon every commit.  This combined with the now-working jenkins is probably sufficient for now.  Feel free to re-open if now.
