### ISSUE TITLE
Does conda-build-all check if package exists on binstar before or after building?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#131]
It seems like the Jenkins builds are still taking a very long time even though few projects need to be rebuilt.  Does `conda-build-all` check binstar *before* or *after* building each package?  Are there other ways to potentially speed this up?

**Comment by kyleabeauchamp** [comment]
There are probably several packages that are missing on binstar because of the SSL upload issue.  For example, gaff2xml: https://binstar.org/omnia/gaff2xml/files

I wonder if there's some weird issue with the ambermini files or something.  Not sure.

**Comment by rmcgibbo** [comment]
> Does conda-build-all check binstar before or after building each package?
[See code](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L205-L212). It checks before.
