### ISSUE TITLE
ambermini OSX libgfortan runtime dependency?

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#132]
This is on my os-x laptop:

```
$ conda install ambermini
[... snip ...]
$ sqm
dyld: Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/rmcgibbo/miniconda/envs/3.4.2/bin/sqm
  Reason: image not found
```

**Comment by kyleabeauchamp** [comment]
Is there a way around this besides just reminding users to have gfortran?  AFAIK there's no way to do this, although maybe there's some hacky way to use the "features" flags of conda recipes.

**Comment by rmcgibbo** [comment]
Well, something that provides `libgfortran.dylib` could be provided as a runtime dependency. Or maybe the binaries could be statically linked? I'm not really sure.

**Comment by rmcgibbo** [comment]
Something is _possible_, since scipy clearly contains fortran source files and is distributed through conda just fine. But that doesn't mean its easy.

**Comment by rmcgibbo** [comment]
From googling, it appears possible to statically link to libgfortran.
- http://stackoverflow.com/questions/17910684/static-libgfortran-in-library-build
- https://gcc.gnu.org/ml/gcc-help/2013-08/msg00203.html
- https://github.com/JuliaLang/julia/issues/326
