### ISSUE TITLE
pyemma windows build

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#151]
I kindly ask, if it may be possible for some of you guys who have already a working windows build pipeline to create another job for pyemma/jpype/pystallone. Otherwise, I will setup a build pipeline on appveyor and ask for binstar push access.

Best - Martin

**Comment by marscher** [comment]
set it up here http://github.com/marscher/conda-win-pyemma. If one would be so kind to create an API token for binstar, I could directly push our packages to omnia channel.

**Comment by rmcgibbo** [comment]
Martin, what's you binstar username? I can add you as a member of the organization there, so you'll have push access and the ability to generate API keys.

**Comment by marscher** [comment]
Hi Robert, its marscher on binstar. Thank you!

**Comment by rmcgibbo** [comment]
done. you should have access now.

**Comment by marscher** [comment]
@rmcgibbo binstar states I need admin privledges for that operation. What am I missing?
     binstar auth --create -n pyemma --create -o omnia --max-age -1 -s api:write

**Comment by marscher** [comment]
fixed. Thanks to @rmcgibbo and @jchodera for help!

**Comment by jchodera** [comment]
Out of curiosity, @marscher, what was needed to get this to work?

**Comment by marscher** [comment]
Am 18.02.2015 um 12:51 schrieb John Chodera:
> Out of curiosity, @marscher <https://github.com/marscher>, what was
> needed to get this to work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omnia-md/conda-recipes/issues/151#issuecomment-74852395>.
>
I've specified the permission tokens in the wrong way:
its binstar auth ... -s "api:read api:write" not -s "api:read,api:write"
