### ISSUE TITLE
msmbuilder folder name in site-packages

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#154]
I created a new conda environment. These are the folders that ended up in my site-packages

```
./yaml
./requests
./conda_env
./conda
./IPython
./pytz
./markupsafe
./nose
./tornado
./zmq
./numpy
./Cython
./pyximport
./dateutil
./scipy
./PyQt4
./jinja2
./matplotlib
./mpl_toolkits
./pandas
./sklearn
./docutils
./pygments
./numexpr
./tables
./Sphinx-1.2.3-py3.4.egg
./numpydoc
./sphinx
./mdtraj
./msmbuilder-3.0.0-py3.4-linux-x86_64.egg
./simtk
```

Why does `msmbuilder` (and Sphinx) have garbage and `.egg`?

**Comment by rmcgibbo** [comment]
I see the `.egg`, but what do you mean by garbage?

**Comment by rmcgibbo** [comment]
The difference is preseve_egg_dir in the `meta.yaml`. I'm not exactly sure what the tradeoffs around that option are. I remember it being important to turn on or off, from some earlier issue. https://github.com/omnia-md/conda-recipes/blob/master/msmbuilder/meta.yaml#L10

**Comment by mpharrigan** [comment]
Sorry I mean the garbage in the filename, where garbage = version number :)

> The difference is preseve_egg_dir in the meta.yaml. I'm not exactly sure what the tradeoffs around that option are. I remember it being important to turn on or off, from some earlier issue. https://github.com/omnia-md/conda-recipes/blob/master/msmbuilder/meta.yaml#L10

Why is python packaging so weird?

**Comment by rmcgibbo** [comment]
Try removing it in the `-dev` package that's used in the msmbuilder travis-ci? I suspect it can be removed.

https://github.com/msmbuilder/msmbuilder/blob/master/devtools/conda-recipe/meta.yaml

**Comment by rmcgibbo** [comment]
one way to find out.

**Comment by rmcgibbo** [comment]
The place where `preserve_egg_dir` was necessary was #104, fixed by #105.

**Comment by mpharrigan** [comment]
That's interesting. Although I had installed openmm in the new env, and the simtk folder is unadorned

**Comment by rmcgibbo** [comment]
As I recall, I was trying to work around a bug in conda-build, but it may
well have been fixed in the mean time.

**Comment by rmcgibbo** [comment]
I believe this may happen even with `preserve_egg_dir: False`, but can be fixed by changing the build script to run `python setup.py install --single-version-externally-managed`
