### ISSUE TITLE
openmm package post-link script broken?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#159]
On OS X 10.9.5, I am seeing this error when doing `conda install omnia` on a fresh anaconda installation:
```
Linking packages ...
/Users/choderaj/anaconda/bin/.openmm-post-link.sh: line 32: /Users/choderaj/anaconda/bin/python: No such file or directory
```
This line appears to be the culprit:
https://github.com/omnia-md/conda-recipes/blob/master/openmm/post-link.sh#L32

**Comment by jchodera** [comment]
I'm still getting weird errors like this periodically on `osx`:
```
/Users/choderaj/projects/automatic-equilibration-detection/examples/liquid-argon-density/conda-env/bin/.openmm-post-link.sh: line 32: /Users/choderaj/projects/automatic-equilibration-detection/examples/liquid-argon-density/conda-env/bin/python: No such file or directory
```
Does anyone else see this?

**Comment by rmcgibbo** [comment]
bug report: https://github.com/conda/conda-build/issues/401
