### ISSUE TITLE
Build win packages on appveyor?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#160]
In Berlin, @marscher showed me how he is using AppVeyor to build pyemma using a variant of the scripts that @rmcgibbo wrote:
https://github.com/marscher/conda-win-pyemma

I wonder if we could have AppVeyor do incremental builds of conda packages for us on the win platform. There is a time limit of 40 min, but this should be enough to build OpenMM or a few conda packages. If we just change conda-build-all to also try to upload each package immediately after it is built, I think we could incrementally build all of the packages and have this work quite successfully for the future. If speed is an issue, paying for the Pro plan seems like a small price to pay for the convenience, and we would be happy to foot the bill.

What do you guys think?

**Comment by rmcgibbo** [comment]
If someone wants to try this out, that would be great.

-Robert

**Comment by marscher** [comment]
incremental means, that you check all recipes version and build numbers and decide which packages to build?

The procedure is then to manually trigger the job until all packages have been build at least one time (or at least until the huge packages are built).

**Comment by jchodera** [comment]
> incremental means, that you check all recipes version and build numbers and decide which packages to build?

Yes!  We would only build things that need to be updated.  Even if all builds don't complete, the next AppVeyor cycle would build some more packages.  This requires some changes to the current scripts, since we would need to upload each package after building it.

> The procedure is then to manually trigger the job until all packages have been build at least one time (or at least until the huge packages are built).

Yup!

**Comment by marscher** [comment]
this should not be to difficult, despite finding time to do this :)

**Comment by marscher** [comment]
@rmcgibbo Thank you so much for setting this up!

**Comment by rmcgibbo** [comment]
np. i'll close his issue, since we've got everything running relatively smoothly now.
