### ISSUE TITLE
64 bit windows builds

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#169]
It looks like few packages are being built for 64 bit windows

https://conda.binstar.org/omnia/win-64

Is there a major barrier to building these?

**Comment by rmcgibbo** [comment]
I don't think so. I was doing the windows builds on an ec2 vm, and only did 32 bit.

**Comment by rmcgibbo** [comment]
Not all of the compiler packages include 64 bit support. I think you need the SDK compilers, described https://github.com/cython/cython/wiki/CythonExtensionsOnWindows#using-windows-sdk-cc-compiler-older-method

**Comment by mpharrigan** [comment]
I build a couple of these on my machine. Is there a mechanism by which I can upload them to omnia?

**Comment by mpharrigan** [comment]
I put them here https://binstar.org/mpharrigan

**Comment by rmcgibbo** [comment]
SWEET!

Do you have an account on binstar.org? I can add your username to the omnia organization to give you the permissions.

**Comment by rmcgibbo** [comment]
Nevermind. Obviously you do.

**Comment by rmcgibbo** [comment]
You should have permissions now. You can upload the files into the omnia org with `binstar upload -u omnia ...`  I think.

**Comment by rmcgibbo** [comment]
What steps did you have to follow to get the 64-bit env up and running?

**Comment by mpharrigan** [comment]
This is going to be somewhat unsatisfactory:

I must have accumulated the compilers over the years. `python setup.py install` works fine without messing with the env et al. per that cython doc. It says it's using 

```
Microsoft (R) C/C++ Optimizing Compiler Version 17.00.61030 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

I have many of the windows sdks installed and it seems to be finding the right one as well

**Comment by mpharrigan** [comment]
That being said, appveyor has a whole slew of compilers and sdks as well

http://www.appveyor.com/docs/installed-software

**Comment by rmcgibbo** [comment]
Fair enough. I didn't realize they all worked together so well.

**Comment by jchodera** [comment]
We should really find a way to get appveyor-based incremental builds working based on the stuff that @marsher has done with [`pyemma`](https://github.com/marscher/conda-win-pyemma) builds.  I just haven't had time to play with this yet.

**Comment by mpharrigan** [comment]
I'm going to try playing with it in the near future

**Comment by rmcgibbo** [comment]
Re appveyor, it looks like the team at ioos/conda-recipes has gotten a system up and running. They're using some tooling from https://github.com/pelson/Obvious-CI which seems to handle some of the cross platform issues. Might be a good place to start from.

https://github.com/ioos/conda-recipes/blob/master/appveyor.yml

**Comment by rmcgibbo** [comment]
Done.
