### ISSUE TITLE
Update versions for external packages

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#178]
```
rmcgibbo@MacBook-Pro  ~/projects/conda-recipes () ‹master›
$ check-outdated
behave-1.2.4 outdated. version 1.2.5 is on pypi
ecos-1.1.0 outdated. version 1.1.1 is on pypi
jpype1-0.5.7 outdated. version 0.6.0 is on pypi
numdifftools-0.6.0 outdated. version 0.7.7 is on pypi
pybtex-docutils-0.2.0 outdated. version 0.2.1 is on pypi
python-coveralls-2.4.3 outdated. version 2.5.0 is on pypi
sphinxcontrib-bibtex-0.3.1 outdated. version 0.3.2 is on pypi
```

**Comment by kyleabeauchamp** [comment]
Should we check whether we are safe to upgrade these without breakage?  In particular, do our docs build with the newest versions of sphinxcontrib etc?  

@marscher  do you have comments on the jypype version?  I imagine that dependency is a tricky one to get right...

**Comment by rmcgibbo** [comment]
I suspect most of them are pretty harmless, since they're just micro version bumps. But obviously I don't really know. Perhaps it would be reasonable to go look at each projects' changelog.

**Comment by kyleabeauchamp** [comment]
@bas-rustenburg is our chief behave user

**Comment by jchodera** [comment]
We could potentially make a separate branch of `omnia-md/conda-recipes` for testing and have a Jenkins job build that branch and push the binaries to a separate binstar channel.

**Comment by rmcgibbo** [comment]
I don't think we need to overthink this, or overengineer it.

We just update the versions. If the new versions are broken, then we can either remove them, or pin the dependencies of things that rely on them to point to the old versions.

**Comment by kyleabeauchamp** [comment]
I'm happy with this approach, I just wanted to ping people to see if anyone knew of any known issues.

**Comment by jchodera** [comment]
OK, sounds fine to me.
