### ISSUE TITLE
Add "skip list"

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#197]
We should add a "skip list" somewhere of packages that either don't build on windows, don't build on py3, or whatever.

As it is currently, on every commit all of the CI systems waste a lot of effort downloading the prerequisites and setting up the build only to have it fail for some of these combinations that we know aren't supported.

**Comment by jchodera** [comment]
What about having each package recipe have a file that lists supported versions of things, like Python versions and platforms?  Like
```
osx-64 win-32 linux-64
py27 py33 py34
```

**Comment by rmcgibbo** [comment]
I don't really want to mess with the conda recipe format though. Also, the assumption that "unless otherwise specified, try to build it with every combination" seems better than the alternative.

**Comment by jchodera** [comment]
Why would this mess with the recipe format?  Wouldn't additional files be ignored?

We can still have the script try to build everything if this file is not present in the recipe directory.

I think we should avoid having one big file that aggregates information about all recipes.  Having separate files in each recipe directory ensures that individual package maintainers can control what gets built for their package (if desired) without fear of collisions.

**Comment by rmcgibbo** [comment]
Closed by #200
