### ISSUE TITLE
change jenkins config to auto-upload

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#217]
@jchodera: can you change the jenkins config to pass the `--upload omnia` flag to `conda-build-all` so that the packages will be uploaded incrementally? The script now has that ability but it looks like it isn't currently in use

https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/configure
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/configure

**Comment by jchodera** [comment]
Done!  Does it access the encrypted binstar token itself?

**Comment by jchodera** [comment]
Maybe you can check if I've done this correctly?

**Comment by rmcgibbo** [comment]
yeah it pulls the token from the env https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L17

**Comment by rmcgibbo** [comment]
yeah, lgtm. do you want to kick off the linux build again (the mdtraj 1.4.2 build didn't get uploaded for linux, but it did for os x).

**Comment by jchodera** [comment]
Building!

**Comment by rmcgibbo** [comment]
cool. thanks john!
