### ISSUE TITLE
pyemma issues 

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#227]
@marscher and @franknoe: There seems to be some problem building the conda package for `bhmm` on `linux` due to issues with the `pyemma` conda package having built on a too-recent version of `libc`:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/127/consoleFull
```
======================================================================
ERROR: test_discrete_6_3 (bhmm.tests.test_init.TestHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.2.0-py2.7-linux-x86_64.egg/bhmm/tests/test_init.py", line 72, in test_discrete_6_3
    import pyemma.msm.generation as msmgen
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/__init__.py", line 31, in <module>
    from . import coordinates
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/coordinates/__init__.py", line 75, in <module>
    from .api import *
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/coordinates/api.py", line 35, in <module>
    from pyemma.coordinates.pipelines import Discretizer as _Discretizer
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/coordinates/pipelines.py", line 24, in <module>
    from pyemma.coordinates.clustering.interface import AbstractClustering
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/__init__.py", line 42, in <module>
    from .assign import AssignCenters
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/assign.py", line 32, in <module>
    from pyemma.coordinates.clustering.interface import AbstractClustering
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/interface.py", line 35, in <module>
    from pyemma.coordinates.clustering import regspatial
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-1.2.1-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/regspatial.so)
```

**Comment by marscher** [comment]
Am 17.06.2015 um 21:52 schrieb John Chodera:
> @marscher <https://github.com/marscher> and @franknoe
> <https://github.com/franknoe>: There seems to be some problem building
> the conda package for |bhmm| on |linux| due to issues with the |pyemma|
> conda package having built on a too-recent version of |libc|:
mhm, well its latest Debian stable (on travis-ci). Maybe you should 
consider upgrading your OS. Which distro/version are you using?

**Comment by jchodera** [comment]
Jenkins is building on a particular CentOS image with an older libc to ensure maximum compatibility with user systems.  Many clusters, for example, run older stable versions of CentOS due to things like ROCKS only supporting certain versions.

Can we instead build `pyemma` on this Jenkins image to make it compatible with more systems?

**Comment by rmcgibbo** [comment]
ya, this is why we don't build the omnia conda binaries on travis-ci. the decision was made a while ago, iirc, that we want to support RHEL6. Ubuntu 12.04 (on travis-ci) uses a later version of glibc, (2.15 vs. 2.12), so you can't build binaries on it with the requisite portability.

**Comment by jchodera** [comment]
Could we build the conda package directly instead of going through pip?  That way you can still distribute the pip one with more recent libc requirements and we can build omnia compatible versions through Jenkins.

**Comment by rmcgibbo** [comment]
@jchodera i'm not sure i follow you. `pip` doesn't install any compiled binaries for linux, it just downloads the source package from pypi. glibc madness is only a variable relevant for compiled binaries.

**Comment by jchodera** [comment]
My understanding was that @marscher was deploying pyemma to pypi and then
using the pypi image via pip to install in the conda recipe, rather than
building pyemma directly in the conda recipe, but I may be confused here.

**Comment by jchodera** [comment]
Ah, they're just retrieving the source from pypi:

https://github.com/omnia-md/conda-recipes/blob/master/pyemma/meta.yaml

**Comment by rmcgibbo** [comment]
most of our recipes pull the source package from https://github.com/omnia-md/conda-recipes/blob/master/behave/meta.yaml#L7. for linux, pypi doesn't host any compiled objects anyways (it does host wheel files for os x and windows, but that's a different matter).

**Comment by jchodera** [comment]
So is the problem just that the pyemma builds on binstar omnia were not
built on Jenkins?

@marscher: Jenkins should be building all of the linux and osx packages in
omnia-md/conda-recipes. I think you just need to disable your other
automated builds.  @rmcgibbo also has an appveyor building the win
packages, so I think you can disable that too.

**Comment by marscher** [comment]
Ah you unified they whole build process. That would have been a good 
thing to know half a year ago, would have save lots of headaches. I'll 
disable the automatized builds in favor of a centralized system then.

So for future versions it is then sufficient to just update the recipe here?

**Comment by jchodera** [comment]
@marscher: it was the other way around!  We had the Jenkins builds for
Linux and OSX working for some time, but your appveyor work inspired
@rmcgibbo to do this for the rest of the conda packages.  So don't think
the effort was wasted!

All that is needed now is to update the conda recipes.

**Comment by jchodera** [comment]
Though I am curious what you had been using to build OSX packages...

**Comment by marscher** [comment]
I build them with travis (trick is to use language: objective-c and
install miniconda).

https://github.com/marscher/conda-win-pyemma

**Comment by jchodera** [comment]
Can you point me to an example?  We might want to do this as well...

**Comment by marscher** [comment]
Sorry, have look here:

https://github.com/marscher/conda-win-pyemma/blob/master/.travis.yml

**Comment by jchodera** [comment]
Thanks! Let me give this a try.

Once you have disabled package builds on your end (temporarily switch
Travis and appveyor off?) can you commit a build number bump for the
recipes you were building that way?

**Comment by marscher** [comment]
Am 18.06.2015 um 16:37 schrieb John Chodera:
> Thanks! Let me give this a try.
> 
> Once you have disabled package builds on your end (temporarily switch
> Travis and appveyor off?) can you commit a build number bump for the
> recipes you were building that way?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omnia-md/conda-recipes/issues/227#issuecomment-113175679>.
> 
My conda builds are semi-automized. I trigger them manually.

I'll prepare a pull request with new build numbers then. Thank you all
for your effort to get this build chain running!

**Comment by marscher** [comment]
done in #231

**Comment by marscher** [comment]
This issue should be gone now.

**Comment by marscher** [comment]
@rmcgibbo please close this :+1:
