### ISSUE TITLE
openmm-dev out of date

### ISSUE THREAD

**Issue by swails** [omnia-md/conda-recipes#235]
The `openmm-dev` package seems to be rather inconsistent with regards to updating its package in the binstar repo.  ParmEd uses this package and its Travis tests are currently failing because some of the unit package bug fixes I've implemented in recent PRs aren't included in the `openmm-dev` package.

I went to https://binstar.org/omnia/openmm-dev/files and downloaded all 6 packages (Linux and OS X packages for Pythons 2.7, 3.3, and 3.4).  The git revisions for each are scattered across recent OpenMM commit history (very helpful to have that in, by the way!):

OS version | Python version | git revision
-------|-------|--------
Linux | 2.7 | 96f0c0f2df52dcd80561219a6faaddab4747a170
Linux | 3.3 | 96f0c0f2df52dcd80561219a6faaddab4747a170
Linux | 3.4 | 0b4a1077f5626389c85492413fbfc0910f11ed8c
OS X | 2.7 | 38076a55aeba2a51b0603ee96fbe7f30ab8344b7
OS X | 3.3 | 38076a55aeba2a51b0603ee96fbe7f30ab8344b7
OS X | 3.4 | 1f0e141bda212237080b5bc4a65aeb9960d90ebf

I need at least revision 1f0e141bda212237080b5bc4a65aeb9960d90ebf (38076a is the latest).  All of the Linux packages are too old for the ParmEd Travis tests.

**Comment by jchodera** [comment]
At @rmcgibbo's request, the recipe for `openmm-dev` has been moved to its own repo:
https://github.com/omnia-md/openmm-dev

Please move this issue there.

Also, I believe this is due to this:
https://github.com/omnia-md/openmm-dev/issues/5

**Comment by jchodera** [comment]
@swails: Jenkins seems to have run successfully and updated all the packages in the last few hours after I cleared the old ones out manually.  

Can you check if things are working OK for you now?

**Comment by jchodera** [comment]
Whoops, wrong thread!
