### ISSUE TITLE
Should packmol.exe go to Anaconda\Scripts?

### ISSUE THREAD

**Issue by sallai** [omnia-md/conda-recipes#283]
A clean installation of conda on windows adds the Anaconda and Anaconda\Scripts directories to the system path (but not Anaconda\bin). Packmol installs the packmol.exe executable to Anaconda\bin though. How about putting it into Anaconda\Scripts? This would eliminate the need of messing around with the path on Windows.

**Comment by jchodera** [comment]
That's surprising!  This does sound like a reasonable solution.

**Comment by rmcgibbo** [comment]
This is probably my fault. IIRC, I needed to hack the toolchain a little bit to build this on windows because I don't intel fortran compilers, so I did it semimanually with mingw64. I don't remember exactly.

**Comment by rmcgibbo** [comment]
I just pushed new binaries that fix this problem. Let me know if you have any trouble.

**Comment by sallai** [comment]
All's good now. Thanks.
