### ISSUE TITLE
Modeller now conda-installable

### ISSUE THREAD

**Issue by danielparton** [omnia-md/conda-recipes#287]
Since Modeller is now conda-installer via the [salilab channel](https://conda.anaconda.org/salilab/), the latest Ensembler release includes this is as a dependency in meta.yaml.
But how do we have `conda-build-all` use external conda channels? Or should we instead be adding Modeller as a package here in `omnia-md/conda-recipes`?

**Comment by rmcgibbo** [comment]
I think you add that channel to the conda config.

**Comment by danielparton** [comment]
Ah ok I see now.

A couple of implementation options:

1. define additional conda channels in `conda-build-all` and have them all added to the conda config before commencing builds, using the command `conda config --add channels https://conda.anaconda.org/salilab`

2. define additional conda channels per package in a newline-separated file named "`additional_conda_channels`" - the contained URLs would then be added to the `conda-build` call with the `-c` flag, for that package only

Any preference?
I think 2 may be best, since it only uses the additional channels for the packages which actually need them, avoiding potential conflicts.

**Comment by mpharrigan** [comment]
If the end user has the omnia channel but not salilab, won't the installation fail for them?

**Comment by rmcgibbo** [comment]
Why not just add it to the channels available in the jenkins/appveyor machine's config, and leave `conda-build-all` alone?

**Comment by rmcgibbo** [comment]
Also, you could just copy over the conda packages into our channels (`binstar copy`)?

**Comment by danielparton** [comment]
The `binstar copy` approach sounds good, since it also means the end user doesn't have to add the `salilab` channel.
@jchodera any thoughts? I don't have access to the jenkins/appveyor config myself.

**Comment by rmcgibbo** [comment]
I can add you to the anaconda.org/binstar.org organization what's your username?

**Comment by danielparton** [comment]
`dannyparton`
Thanks!

**Comment by rmcgibbo** [comment]
done

**Comment by danielparton** [comment]
Ok, that seems to have worked - thanks! Submitting PR with new Ensembler meta.yaml now.
