### ISSUE TITLE
Appveyor doesn't build py33 on win

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#306]
I forget if there's a specific reason that Appveyor doesn't build py33 packages on `win`.  Was that because OpenMM requires py34 on win?

**Comment by rmcgibbo** [comment]
I think it was just speed of debugging. The whole matrix needs to finish in less than the 40 minute cutoff. We should probably enable py27 before py33 though.

**Comment by jchodera** [comment]
Can OpenMM build py27 on `win`?

**Comment by rmcgibbo** [comment]
No, but there are other packages in this collection besides OpenMM.

**Comment by rmcgibbo** [comment]
Also, the OpenMM binaries on binstar.org aren't actually built on appveyor (no CUDA, OpenCL).

**Comment by jchodera** [comment]
Ah, right.  So we would just need to be careful about setting up `skip.yaml` for OpenMM-dependent packages.

**Comment by rmcgibbo** [comment]
Start #307, see if it works.

**Comment by rmcgibbo** [comment]
I enabled py27-x64. Seemed to work. Probably do py27-x32 next.

**Comment by jchodera** [comment]
Thanks!
