### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#324]
Python 3.5.0 was just released. We should probably add it to the build matrix going forward for new packages / versions. For windows, this also means building extensions with VS2015.

**Comment by peastman** [comment]
For Windows, it's basically either/or.  Different VS releases aren't binary compatible with each other, so we have to compile *everything* with the same version.

I'm totally fine with moving to Python 3.5 only on Windows and compiling with VS 2015.  It would mean we could finally start using C++11 features!

**Comment by rmcgibbo** [comment]
We have seperate conda binaries for each version of Python. So we can release both py34/VS2010 binaries and py35/VS2015 binaries.

**Comment by peastman** [comment]
Right, but that would mean we still couldn't use C++11.

**Comment by rmcgibbo** [comment]
These are two separate conversations. The first conversation (this issue) is that omnia-md should put in place the machinery for building binaries against py3.5. That applies to how we build binaries for lots of packages, not just OpenMM.

The second issue, what you're bringing up, is an OpenMM-specific issue of what version of VS you want to support on windows -- either VS2010 & VS2015 or VS2015-only. The two issues are somewhat independent.

**Comment by rmcgibbo** [comment]
This is done.
