### ISSUE TITLE
Add cpptraj

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#340]
It would be nice to add cpptraj, (specifically for my/@mpharrigan's purpose for testing mdtraj on travis-ci, cc: https://github.com/mdtraj/mdtraj/pull/939). The easiest way (no code duplication) would be to add a recipe that builds a specific hash of https://github.com/amber-md/cpptraj. Does this seem reasonable? cc @swails.

**Comment by hainm** [comment]
you can use `conda install libcpptraj-dev -c ambermd`

it comes with `cpptraj.OMP` (openmp version). For Linux build only.

**Comment by rmcgibbo** [comment]
Okay, that's easy. If we add it here, we'll get OS X and windows builds for free, but for the current use case linux is sufficient.

**Comment by hainm** [comment]
> we'll get OS X and windows builds for free

it's really great if you can make it works. We never have luck with OSX and Windows (actually not tried hard).

**Comment by rmcgibbo** [comment]
Well, "free" depends on the package actually compiling successfully. If you haven't tried, I doubt it'll 'just work'. :)

**Comment by hainm** [comment]
> If you haven't tried, I doubt it'll 'just work'. :)

not tried hard.

https://travis-ci.org/hainm/cpptraj/builds/84416119

**Comment by rmcgibbo** [comment]
This is done.
