### ISSUE TITLE
Numpy 1.10

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#342]
We should start building packages (that link to numpy abi) for numpy 1.10 too. This is currently broken in conda-build if you use environment variables https://github.com/conda/conda-build/issues/631

**Comment by jchodera** [comment]
Was @rmcgibbo going to try to tackle that (per #338) or does this still need doing?

**Comment by mpharrigan** [comment]
They're somewhat separate issues

@rmcgibbo is going to fix recipes so they aren't broken. Since we explicitly set numpy version, we don't automatically get whatever's newest on conda

It's most similar to #324 insofar as we need to explicitly enable building against a newer release of something

**Comment by rmcgibbo** [comment]
Done.
