### ISSUE TITLE
omnia osx-64 not available?

### ISSUE THREAD

**Issue by franknoe** [omnia-md/conda-recipes#360]
We just got the following problem report that I can reproduce on my machine. It seems that osx-64 packages are currently not available. Any ideas?

```
$ conda config --add channels http://conda.binstar.org/omnia
$ conda install binstar
Fetching package metadata: .....Error: Could not find URL: http://conda.binstar.org/omnia/osx-64/
$ conda install pyemma
Fetching package metadata: .....Error: Could not find URL: http://conda.binstar.org/omnia/osx-64/
```

**Comment by jchodera** [comment]
Looking into this now!

**Comment by jchodera** [comment]
Note that the `binstar` package no longer exists; it is now called `anaconda-client`, and the binary is called `anaconda`.  This change was made only recently by Continuum.

See https://github.com/pandegroup/openmm/issues/1202 for more information.

**Comment by jchodera** [comment]
I believe you can specify just
```
conda config --add channels omnia
```
now to add the channel.

To install `pyemma`, you can even just use
```
conda install -c omnia pyemma
```

**Comment by jchodera** [comment]
All `osx` packages for `pyemma` are indeed up:
```
https://anaconda.org/omnia/pyemma/files
```
The latest version is `pyemma 2.0.1`, which was released about 45 days ago.  Let me know if you are still having trouble.
