### ISSUE TITLE
Binstar.org to Anaconda.org movement causes Jenkins to fail

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#362]
Please change the addition of the omnia channel in the Jenkins jobs to 

```
conda config --add channels omnia
```
This will implicitly direct to the new anaconda.org server.

@jchodera this is somehow urgent, as I have to push a new release today. Thank you very much!

**Comment by marscher** [comment]
the osx has this malformed channel

**Comment by marscher** [comment]
Appveyor has this issue:

```
conda config --add channels omnia
conda config --add channels salilab
conda update -yq --all
Fetching package metadata: ....Error: Could not find Binstar user omnia
Command exited with code 1
```

Maybe we need to install anaconda-client first?

**Comment by jchodera** [comment]
Thanks for catching this!  I had tried to update everything on Jenkins, but had missed this.

Sorry for the slow response---on a Lufthansa flight near Greenland, and the internet isn't super-fast.

I'm trying to update this, but don't seem to be having any luck from the air.  Will keep trying.

**Comment by marscher** [comment]
Fixing Jenkins jobs from a plane does not sound like an easy task :-)

Maybe try ssh tunneling with compression enabled to reduce the traffic a 
bit.

# assuming jenkins listens on port 8080
ssh -L8080:localhost:8080 host
firefox localhost:8080

Thanks for your effort!

**Comment by jchodera** [comment]
Unfortunately, I can't connect to the server via ssh except through a bandwidth-hogging VPN.

I'm trying to see if I can get someone in my lab to help out.  I'll definitely train someone to be a backup Jenkins manager in case this happens again in the future.

**Comment by jchodera** [comment]
I think I changed the channel and triggered a new build.  Can you see why it is failing now?

**Comment by marscher** [comment]
now it is the same output as on Appveyor.
```
Fetching package metadata: ....Error: Could not find Binstar user omnia
```

**Comment by marscher** [comment]
If I use the same miniconda installer version (3.9.1) I can reproduce the issue locally. So it might worth upgrading the installer requirement.

**Comment by marscher** [comment]
conda update -qy conda before adding the channel might also do the trick.

**Comment by marscher** [comment]
This change of important production servers name is really annoying and unprofessional. Did you receive an email about it, since you are paying them for some additional space?

**Comment by marscher** [comment]
Instead of using an old installer and updating all packages (which seems to be the default behaviour of conda update), we should consider using the "latest" symlink of http://repo.continuum.io/miniconda/

**Comment by jchodera** [comment]
Trying that now.

Agreed about the sudden changes without notification.  They did warn us about the binstar to anaconda migration, but not about the package name changes.  In fact, they changed the package name **three times in three days**, which is a great way to piss off a bunch of people.

**Comment by jchodera** [comment]
We were previously doing that, but then they updated something in a new version and things broke.  I then switched back, thinking that sticking with a known stable version would be better.  Ha!

**Comment by marscher** [comment]
Maybe one can enforce "stable" versions via pinning them in an extra 
file, which can the be used no matter which build system is used.

conda env --export -n my_super_stable_build_env --file build.env

put build.env into the repo and use it to reproduce a "sane" pre-build env.

**Comment by marscher** [comment]
Looks like it is working again.

**Comment by marscher** [comment]
Ah sorry my mistake, I just looked at the linux output. Which is not broken for some reason.

**Comment by marscher** [comment]
I guess this is resolved?
