### ISSUE TITLE
Some Python3.3 binaries are missing

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#370]
For example the (new) bhmm release 0.5.2 has not been built for Python3.3, which blocks PyEMMA's Travis tests from passing, since the new version can not be installed for this Python branch.
```
(py33)marscher@jigsaw:~/workspace/pyemma$ conda search bhmm|grep 0.5.2
                             0.5.2                np19py35_0  omnia           
                             0.5.2                np19py34_0  omnia           
                             0.5.2                np19py27_0  omnia           
                             0.5.2               np110py35_0  omnia           
                          .  0.5.2               np110py34_0  omnia           
                          .  0.5.2               np110py27_0  omnia 
```

**Comment by jchodera** [comment]
Hm.  It looks like the py33 package build isn't even being attempted:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/253/consoleFull

**Comment by marscher** [comment]
But we used to have Python3.3, so why did we change this policy?

**Comment by jchodera** [comment]
It appears that 33 has been eliminated from the default build list:
https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L82

**Comment by jchodera** [comment]
@rmcgibbo eliminated it in #351 when adding py35:
https://github.com/omnia-md/conda-recipes/commit/0bba21baa343fd6a82f344e34b54442f70abbf0a

I don't know if that was intended or not, but we should probably restore 33.

**Comment by jchodera** [comment]
Can you create a PR to restore py33, @marscher?

**Comment by rmcgibbo** [comment]
Nobody is using py33.

**Comment by rmcgibbo** [comment]
Comtinuum isn't buidling new packages for py33 either. People that are using py3 have no barrier to upgrade to the latest minor releases.

**Comment by jchodera** [comment]
By "nobody" do you mean "nobody in the field", or "none of our projects", because the latter is not correct.

In any case, support for major Python versions should probably be discussed before being dropped silently in a PR about something else.

**Comment by rmcgibbo** [comment]
No *user* (or at the very least an insignificant number who have a roadblock-free upgrade path to py34 or py35) are using py33. The download counts are on anaconda.org. They're all ~ zero.

**Comment by jchodera** [comment]
OK, so we should deprecate py33 across all projects.  We can totally do that---but as you can see, removing `py33` builds without warning has just broken lots of travis testing.

**Comment by rmcgibbo** [comment]
```
$ conda search numpy 
[... scroll down to latest release ...]
                             1.10.1                  py35_p0  defaults        [mkl]
                          .  1.10.1                   py35_0  defaults
                             1.10.1                  py34_p0  defaults        [mkl]
                          *  1.10.1                   py34_0  defaults
                             1.10.1                  py27_p0  defaults        [mkl]
                          .  1.10.1                   py27_0  defaults
```

**Comment by mpharrigan** [comment]
+1 no py33. no reason to keep building packages literally no one will use or should use

**Comment by jchodera** [comment]
That makes sense, but we need to spread the word that literally *every* package now must remove py33 from their build/test matrix.

**Comment by rmcgibbo** [comment]
LOL. ALERT.

**Comment by rmcgibbo** [comment]
I think people will figure it out. Probably everyone who "the word must be spread to" is on this thread.

**Comment by jchodera** [comment]
> LOL. ALERT.

Thanks.  Give us a bit more heads up next time you break everything?  :)

**Comment by jchodera** [comment]
Dumb question: Does deprecating py33 mean anything for reproducibility?  Looks like the old versions of numpy are still available for py33, yes?  So old versions of packages will still work?

**Comment by rmcgibbo** [comment]
None of the old packages are gone. Just a question of what we build for new ones.

**Comment by mpharrigan** [comment]
Going forward, I think a good plan is to build for two latest python releases and py2.7. If we stick to this, there shouldn't be any surprises

**Comment by swails** [comment]
+1

**Comment by jchodera** [comment]
> Going forward, I think a good plan is to build for two latest python releases and py2.7. If we stick to this, there shouldn't be any surprises

Sounds reasonable!

**Comment by marscher** [comment]
Agreed.
