### ISSUE TITLE
Add RDKit

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#381]
Assigning @rbharath :)

**Comment by jchodera** [comment]
Isn't there already [an official recipe](https://github.com/rdkit/conda-rdkit/tree/master/rdkit) and [an official conda package](https://anaconda.org/rdkit/rdkit)?

**Comment by rmcgibbo** [comment]
Yeah, so it should be easy. But it hard-depends on a different boost than the one here, etc.

**Comment by jchodera** [comment]
To be clear: We need to build our own recipe because the [official RDKit conda package](https://anaconda.org/rdkit/rdkit) depends on different library versions than the ones we use on omnia?

**Comment by rmcgibbo** [comment]
Yes, I think that's correct. Mostly I was kind of ribbing @rbharath with this issue, because he was saying that this was on his agenda. I don't know all the technical details.

**Comment by jchodera** [comment]
Was asking just because I was talking with some folks yesterday who wondered what happens when we run into an issue where two different sets of conda-installed tools are linked to different versions of the same dynamic library.

**Comment by rmcgibbo** [comment]
- If the packages fully declare their dependencies, like "X depends on lib==1.5", "Y depends on lib==1.6", and you try to install both X and Y into the same environment, the resolver will say there's a conflict (it just solves a SAT problem), and refuse.
 - If one packages fully declares its dependencies but the other doesn't, like "X depends on lib", "Y depends on lib==1.6", then it'll install both. But if X _actually_ has a binary dependency on lib==1.5, and the library isn't binary forward compatible (very rare), then you'll get into a broken state.

**Comment by jchodera** [comment]
Thanks!  I guess the proper way to do this is to explicitly declare those dependencies as "X depends on lib>=1.5" and make sure any dynamic library dependencies are appropriately packaged as conda packages, rather than distributed along with the conda package for the tool linking them.

**Comment by rmcgibbo** [comment]
For boost, the real solution is just to get a proper boost package in the default channels.

**Comment by rbharath** [comment]
@jchodera: There are also a couple other issues with the standard conda-rdkit build besides boost library version. For example, there's a test that I have to manually disable each time I build to get it to work out right.

**Comment by marscher** [comment]
currently rdkit blocks travis osx builds because it needs more than 40 min (maximum wall time of travis). Maybe try invoking make with at least two jobs as it might speed things up.
