### ISSUE TITLE
Can't delete older packages on anaconda cloud

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#408]
I noticed that uploads of the `dev` packages for `openmmtools-dev` were failing because the packages couldn't be deleted even with the `anaconda upload --force` argument.

It turns out I can't delete them through the web interface or command-line API either.
Can someone see if they can remove the `dev` version packages from here?
https://anaconda.org/omnia/openmmtools-dev/files

Any idea where I would report this issue?

**Comment by rmcgibbo** [comment]
Looks like it was reported at https://github.com/Anaconda-Server/support/issues/11?

**Comment by mpharrigan** [comment]
Has this been fixed?

**Comment by jchodera** [comment]
Yes! I can't remember precisely when, but they implemented the delete button some time back.
