### ISSUE TITLE
Upload to anaconda cloud not working

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#421]
@rmcgibbo: Any idea why `conda-build-all` is trying to upload `noarch` packages when these should be dependent on a particular architecture?

See travis logs:
```
# $ anaconda upload /anaconda/conda-bld/linux-64/openmm-6.3.1-py35_1.tar.bz2

#

# To have conda build upload to anaconda.org automatically, use

# $ conda config --set anaconda_upload yes



ERROR: File does not exist: /anaconda/conda-bld/noarch/openmm-6.3.1-py35_1.tar.bz2
```

**Comment by rmcgibbo** [comment]
Probably a bug in #417

**Comment by rmcgibbo** [comment]
https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L184-L185 maybe needs an else statement/?

**Comment by jchodera** [comment]
Thanks!
