### ISSUE TITLE
win32 py27 scripttest md5 mismatch

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#428]
Would somebody with the knowledge to remove this faulty package from index please be so kind and delete it, so it will be built again.

```
Error: MD5 sums mismatch for download: https://conda.anaconda.org/omnia/win-32/scripttest-1.3-py27_0.tar.bz2 (c09fc3369454e6034a51e668087b5331 != e6962f95e4c8861ef34d9b739dbf925e)
```

**Comment by rmcgibbo** [comment]
If you don't have enough permissions on the omnia org on anaconda.org, we should add that?

**Comment by rmcgibbo** [comment]
Also, I just tried downloading the file from anaconda.org, and the md5 matches what the web UI says it should be (c09fc...), so the problem in #427 might have been something different.

**Comment by rmcgibbo** [comment]
i just tried deleting it anyways.

**Comment by jchodera** [comment]
I can't seem to figure out how to add people to the organization.  Since they changed the UI, I think some functionality might just be well hidden or possibly even nonexistent...
