### ISSUE TITLE
Use omnia-md organization settings effectively

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#432]
Echoing @mpharrigan's suggestion on the MDTraj organization https://github.com/mdtraj/mdtraj/issues/1033. It would probably be a good idea to use the organization settings more effectively here as well.

**Comment by jchodera** [comment]
I *think* I did this now, but it is very non-obvious how to do what @mpharrigan suggested.

**Comment by mpharrigan** [comment]
@jchodera : there should be a big banner at the top that says "we've made oranization settings easier!" or whatever. Click take the tour and it walks you through step by step

**Comment by mpharrigan** [comment]
(and let's you change the settings via the tour. It puts a nice green "recommended" label next to the new settings)

**Comment by jchodera** [comment]
Oh!  Thanks!

**Comment by mpharrigan** [comment]
No problem!
