### ISSUE TITLE
Some problem with pyemma

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#448]
cc @marscher, there's some problem with pyemma on the build infrastructure here, at least on mac. it might be a problem with the build script, not with anything in pyemma itself, but it looks like the latest RC it's getting rebuilt every time and then failing to upload
https://travis-ci.org/omnia-md/conda-recipes/jobs/111904741#L1313-L1354

**Comment by rmcgibbo** [comment]
I believe the problem is that the files on Anaconda.org are under the `/pre` label, which tricks the `conda-build-all` script. It doesn't see them, because of the label, so then it tries to rebuild them because it thinks they're missing. But then it fails during upload.

**Comment by jchodera** [comment]
I think @marscher has a PR open with some changes to the build script?

**Comment by rmcgibbo** [comment]
i don't see any open PRs...

**Comment by rmcgibbo** [comment]
im just going to fix this now though.

**Comment by jchodera** [comment]
cc: https://github.com/omnia-md/conda-recipes/issues/445
