### ISSUE TITLE
Possible gpy build problem on win

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#457]
@cxhernandez : Can you check out this error in appveyor?

https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.676/job/vqbsiyopx77oxvxo#L436

**Comment by cxhernandez** [comment]
Seems like appveyor doesn't have openmp support. For now, should I just remove the `bld.bat`?

**Comment by peastman** [comment]
To enable OpenMP in Visual Studio, include the command line option `/openmp`.

**Comment by cxhernandez** [comment]
@peastman: Are you sure appveyor has an omp-enabled version of VS:

```
C:\Miniconda3\conda-bld\work>/openmp
'/openmp' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by peastman** [comment]
Yes, of course.  Visual Studio has supported it for a long time.  But I don't understand what your change was supposed to do.  You just put "/openmp" by itself on a command line, as if it were a program to execute.

The normal way of handling this is in the setup.py script.  Distutils knows what compiler arguments are required by whatever compiler it's using, and provides them in the variable `compiler_args_openmp`.  See, for example, https://github.com/mdtraj/mdtraj/blob/master/setup.py#L230.

**Comment by cxhernandez** [comment]
Ah okay. This isn't my repo, so I'll just make a patch for this then.

**Comment by mpharrigan** [comment]
Is this done?
