### ISSUE TITLE
conda-build-all not working correctly on AppVeyor

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#461]
It seems to building packages that already exist on anaconda cloud:
https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/job/7xnnlho4u9ih00oq

For example:
```
Uploading file omnia/pyemma/2.1rc3/win-32/pyemma-2.1rc3-np19py27_0.tar.bz2 ... 
Distribution already exists. Please use the -i/--interactive or --force options or `anaconda remove omnia/pyemma/2.1rc3/win-32/pyemma-2.1rc3-np19py27_0.tar.bz2`
Using Anaconda Cloud api site https://api.anaconda.org
[ERROR] 
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\anaconda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\binstar_client\scripts\cli.py", line 87, in main
    description=__doc__, version=version)
  File "C:\Miniconda\lib\site-packages\binstar_client\scripts\cli.py", line 66, in binstar_main
    return args.main(args)
  File "C:\Miniconda\lib\site-packages\binstar_client\commands\upload.py", line 206, in main
    callback=upload_print_callback(args))
  File "C:\Miniconda\lib\site-packages\binstar_client\__init__.py", line 416, in upload
    self._check_response(res)
  File "C:\Miniconda\lib\site-packages\binstar_client\__init__.py", line 164, in _check_response
    raise ErrCls(msg, res.status_code)
Conflict: (u'file win-32/pyemma-2.1rc3-np19py27_0.tar.bz2 already exists for package pyemma version 2.1rc3', 409)
detecting package type ...
conda
extracting package attributes for upload ...
done
```

**Comment by jchodera** [comment]
Actually, I think this is due to some of these packages being under the `pre` channel:
https://anaconda.org/omnia/pyemma/files

Some of those files are uploaded from `rmcgibbo` and some from `omnia`.

@rmcgibbo and @marscher : Whatever is going on with the `pre` channel stuff for `pyemma` is fucking up the rest of the builds here.  Any chance you can figure out what is going on?

If not, I think we might have to blow away all the recent `pyemma` projects and retrigger AppVeyor just to unfuck things for everyone else.

**Comment by jchodera** [comment]
Update: 
* It looks like the `rmcgibbo` uploads are because AppVeyor are running under @rmcgibbo's account.
* Some `win` packages are still being correctly built and deployed to anaconda cloud despite the pyemma failures

**Comment by marscher** [comment]
So is it actually an issue? (since the missing win packages are still being deployed)

**Comment by marscher** [comment]
Unfortunately I can not view the Appveyor job output (rights problem I'd guess). In principle this problem should not occur anymore, since it is checked whether a package exists in main and pre channel.

**Comment by marscher** [comment]
The problem was that appveyor did not check against the pre label.

**Comment by jchodera** [comment]
@marsher: Please don't commit directly to the repository!  Always use PRs!

**Comment by marsher** [comment]
@marscher not @marsher :)

**Comment by jchodera** [comment]
Whoops! My apologies, @marsher. :)
