### ISSUE TITLE
conda-build-all failure on osx due to prerelease flags

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#472]
Not sure what [caused this failure](https://travis-ci.org/omnia-md/conda-recipes/jobs/119261980#L9580-L9593):
```
...
Traceback (most recent call last):
  File "./conda-build-all", line 372, in <module>
    sys.exit(main())
  File "./conda-build-all", line 100, in main
    return execute(args, p)
  File "./conda-build-all", line 357, in execute
    code = build_package(m, python, numpy, args)
  File "./conda-build-all", line 307, in build_package
    force=args.force)
  File "./conda-build-all", line 223, in upload_to_binstar
    if not pre_black_listed(m) and is_prerelease(m) :
  File "./conda-build-all", line 325, in pre_black_listed
    if not line.startswith('#') and pkg_meta.name in line:
TypeError: 'in <string>' requires string as left operand, not method
+true
```
Any ideas @marscher @rmcgibbo ?

**Comment by jchodera** [comment]
The failure occurred after building the `openmm 7.0rc1` package before upload to anaconda cloud.

**Comment by marscher** [comment]
Am 29.03.2016 um 18:32 schrieb John Chodera:
> The failure occurred after building the |openmm 7.0rc1| package before
> upload to anaconda cloud.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/omnia-md/conda-recipes/issues/472#issuecomment-202986825>
>
I'll look into this.

**Comment by marscher** [comment]
I didn't mention to close this now via a commit. The strange thing is why this only happened on OSX.

**Comment by jchodera** [comment]
@marscher : Can you please use PRs instead of direct commits?

**Comment by marscher** [comment]
sorry. Of course.

**Comment by jchodera** [comment]
Thanks!
