### ISSUE TITLE
Revisit supported versions of python, numpy

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#476]
Right now, our policy is to support the two most recent python 3 versions plus python 2.7 and the two most recent numpy releases.

I think this is a little overengineered, especially since everyone involved in packaging has a "day job" other than packaging. We run into issues supporting odd configurations that no one is using (python 3.5 and numpy 1.9)

I'd like to open the discussion for dropping support for certain configurations. My ideas are as follows

 1. Drop numpy 1.9. Anyone with conda can and will easily upgrade to numpy 1.10
 2. Drop python 3.4 at some point in the near future. It's nice having both during the "transition" period when python 3.5 wasn't mature. Maybe when 3.5.2 comes out, we can drop support for 3.4
 3. Drop python 2.7 and 3.4 on windows. This would simplify the building of things with compiled extensions a lot, since vs2015 has a much more compliant compiler. Windows users don't have a `/usr/bin/python` stuck on 2.7 that they're clinging to.
 4. Consider dropping python 2.7 at some point. Its EOL is in 2020 (4 years away). Anyone using conda can easily get a newer version of python

Let me know what you all think

**Comment by jchodera** [comment]
> Consider dropping python 2.7 at some point. Its EOL is in 2020 (4 years away). Anyone using conda can easily get a newer version of python

Many of us here are still stuck on python 2.7, so it would be best to avoid dropping that for a little while.

I'm fine with dropping 3.4 now or soon.

**Comment by mpharrigan** [comment]
Thought I might get some push back on that one :)

What are your thoughts on dropping numpy 1.9

**Comment by jchodera** [comment]
> What are your thoughts on dropping numpy 1.9

I don't have a good idea for how much trouble that would cause, so I'm game to give it a try...

**Comment by rmcgibbo** [comment]
I am fine with dropping older numpys, but think it would be a shame to drop older pythons.

**Comment by jchodera** [comment]
Dropping older Pythons also requires a good deal of warning, since we have to update all the `.travis.yml` files to exclude the dropped Python version...

**Comment by peastman** [comment]
Upgrading Python versions is disruptive and a hassle.  Once you get python all set up, and everything you want installed in it, who wants to have to throw it out and do all that work over again?  That's not to say we have to keep supporting them forever, but Python 3.5 was only released in September!  You already want to stop supporting 3.4?

On Windows it's especially complicated due to the issues with binary compatibility.  Python 3.4 and 3.5 were compiled with different versions of Visual Studio, so they can only link to libraries that were compiled with those same versions.

**Comment by mpharrigan** [comment]
Numpy 1.11 was just released. When that becomes available through conda, we can start building packages for that and dropping numpy 1.9
