### ISSUE TITLE
Cuda version mismatch

### ISSUE THREAD

**Issue by jlmaccal** [omnia-md/conda-recipes#486]
I'm working on having Travis automatically build Meld conda packages for testing. I've run into a problem, where the version of cuda doesn't match between published conda packages and the omnia-build-box, which prevents my Meld plugin from linking correctly.

Specifically, I'm trying to build against the version that `conda install openmm` gives, which is 6.3.1. This was built with cuda 7.0. But, the current `omnia-build-box` uses cuda 7.5, which causes [errors during linking](https://travis-ci.org/maccallumlab/meld-openmm-plugin/builds/121973146):
```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-CentOS-linux/4.8.2/ld: warning: libcufft.so.7.0, needed by /anaconda/lib/plugins/libOpenMMCUDA.so, not found (try using -rpath or -rpath-link)
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftPlan3d'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecZ2D'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftSetStream'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecC2R'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecD2Z'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecR2C'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftSetCompatibilityMode'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftDestroy'
collect2: error: ld returned 1 exit status
```

If I can propose a solution, the `omnia-build-box` should be tagged with the cuda version rather than always just using `latest`.

**Comment by peastman** [comment]
Note that we're just about to release OpenMM 7.0 (hopefully on Monday!), which uses CUDA 7.5.

This is still an issue that needs to be addressed as a general case.  But this specific instance is about to go away.

**Comment by jlmaccal** [comment]
So, it turns out I get a similar error, even when building against `openmm-dev`, which uses 7.5 and I'm still getting a similar error:

```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-CentOS-linux/4.8.2/ld: warning: libcufft.so.7.5, needed by /anaconda/lib/plugins/libOpenMMCUDA.so, not found (try using -rpath or -rpath-link)
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftPlan3d'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecZ2D'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftSetStream'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecC2R'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecD2Z'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftGetVersion'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecR2C'
/anaconda/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftDestroy'
collect2: error: ld returned 1 exit status
```

I don't understand this, because cuda-7.5 is installed and `libcufft.7.5.so` is present. Here's the contents of my `build.sh` script. Is there any flag that I'm obviously missing?
```
#!/bin/bash

CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_TESTING=OFF"

CMAKE_FLAGS+=" -DCMAKE_BUILD_TYPE=Release"

CUDA_PATH="/usr/local/cuda-7.5"
CMAKE_FLAGS+=" -DCUDA_CUDART_LIBRARY=${CUDA_PATH}/lib64/libcudart.so"
CMAKE_FLAGS+=" -DCUDA_NVCC_EXECUTABLE=${CUDA_PATH}/bin/nvcc"
CMAKE_FLAGS+=" -DCUDA_SDK_ROOT_DIR=${CUDA_PATH}/"
CMAKE_FLAGS+=" -DCUDA_TOOLKIT_INCLUDE=${CUDA_PATH}/include"
CMAKE_FLAGS+=" -DCUDA_TOOLKIT_ROOT_DIR=${CUDA_PATH}/"
CMAKE_FLAGS+=" -DCMAKE_CXX_FLAGS_RELEASE=-I/usr/include/nvidia/"

export EIGEN3_INCLUDE_DIR="/anaconda/include/eigen3/"
export OPENMM_DIR="/anaconda/"
export OPENMM_INCLUDE_PATH=$OPENMM_DIR/include
export OPENMM_LIB_PATH=$OPENMM_DIR/lib
export LD_LIBRARY_PATH+=$OPENMM_DIR/lib
export LD_LIBRARY_PATH+=$CUDA_PATH/lib64

mkdir build
cd build

ls /anaconda/include

cmake .. $CMAKE_FLAGS
make -j$CPU_COUNT all
make -j$CPU_COUNT install PythonInstall
```

Also, on a more general note, should the `openmm` build be linking against a specific version of the cuda libraries or should it be to the generic link, e.g. `libcufft.7.5.so` vs `libcufft.so`?

**Comment by jchodera** [comment]
> If I can propose a solution, the omnia-build-box should be tagged with the cuda version rather than always just using latest.

Excellent suggestion, @jlmaccal!  I hadn't figured out docker image tags yet, but this is a great excuse to do that now.

**Comment by jchodera** [comment]
Should we tag the `omnia-build-box` releases/versions with the OpenMM version they are used to build or the CUDA version that they use?  `openmm-7.0` or `cuda-7.5`?

**Comment by jchodera** [comment]
@jlmaccal: Are you working on a fork of `conda-recipes`?  If so, could also be useful to open a PR (marked "[WIP]") that we could comment on.

**Comment by jlmaccal** [comment]
@jchodera I would suggest with the cuda version (or an arbitrary version number for the build-box itself. If the `travis.yml` file is changed to use a tagged docker image rather than `latest`, then the provenance will be clear.

**Comment by jchodera** [comment]
How about `cuda-7.5-appsdk-3.0` since both CUDA and AMD APP SDK versions may be relevant?

**Comment by peastman** [comment]
> should the openmm build be linking against a specific version of the cuda libraries or should it be to the generic link, e.g. libcufft.7.5.so vs libcufft.so?

That's a decision NVIDIA has made for us:

```
$ objdump -p /usr/local/cuda/lib64/libcufft.so | grep SONAME
  SONAME               libcufft.so.7.5
```

So anything linking against that library will specify the specific version.  They did that because CUDA versions are not binary compatible across releases.

**Comment by jlmaccal** [comment]
@jchodera Why not just 0.1.0 and then update every time something changes. Presumably there could be other changes besides cuda version?

**Comment by jlmaccal** [comment]
@peastman That sucks... so this means I'm not going to be able to use all of this hard work to install openmm on a cluster with an older version of cuda? Have we thought about building against multiple versions?

**Comment by jchodera** [comment]
@jlmaccal: How are you doing the builds?  Are you using the [`devtools/docker-build.sh`](https://github.com/omnia-md/conda-recipes/blob/master/devtools/docker-build.sh) script?

**Comment by jchodera** [comment]
> @peastman That sucks... so this means I'm not going to be able to use all of this hard work to install openmm on a cluster with an older version of cuda? Have we thought about building against multiple versions?

cc: https://github.com/pandegroup/openmm/issues/1038

**Comment by jlmaccal** [comment]
@jchodera Here's my plan regarding CI:

I want to produce "testing" conda packages that I will test with local jenkins instances that have GPUs. That's what I'm currently trying to build.

I will produce release conda packages by including meld in `condo-recipes`.

Have a look at [maccallumlab/meld-openmm-plugin](https://github.com/maccallumlab/meld-openmm-plugin) to see what I'm currently trying.

**Comment by jchodera** [comment]
> @jchodera Why not just 0.1.0 and then update every time something changes. Presumably there could be other changes besides cuda version?

The GitHub release tags would be the same as the docker image tags, so I thought it might be easier to discern which version you want based on explicitly stating the CUDA and AMD APP SDK versions.

What about `cuda-7.5-appsdk-3.0-v0` or something to allow versioning?

**Comment by jchodera** [comment]
I think it might be easier to debug if you just open a PR for the recipe---even if you end up closing it---for this repo. That way, we can make sure there are no differences in *how* you are doing the build.

**Comment by jlmaccal** [comment]
@jchodera I don't have anything to do a pull request against. I stole code snippets from `condo-recipes`, but I didn't fork it.

Let's move discussion over there: https://github.com/maccallumlab/meld-openmm-plugin/issues/7

**Comment by jchodera** [comment]
You could fork this repo, add your recipe, and open a PR. That's how we normally add recipes. It will build under our same build system and we will be able to see the travis output, though it won't be uploaded to anaconda cloud.
