### ISSUE TITLE
Use labels correctly

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#488]
http://docs.anaconda.org/using.html#UsingLabelsInTheDevelopmentCycle

Procedure for releasing a package where you want to be careful

1. bump version to what you want the final release to be called, e.g. "2.0"
2. upload to a label "rc" (release candidate)
3. when satisfied with the binary package, change the label to "main" *without* rebuilding

For (2), we can use the http://conda.pydata.org/docs/building/meta-yaml.html#extra-section extra section to figure out what label to upload to. 

We can also make everything go to the rc label first, but this might be overkill

**Comment by jchodera** [comment]
+1

I think it might be worthwhile to request a feature to be added to the `meta.yaml` that specifies the label for upload.

**Comment by mpharrigan** [comment]
> I think it might be worthwhile to request a feature to be added to the meta.yaml that specifies the label for upload.

I agree, although that may take a while to get to us

**Comment by mpharrigan** [comment]
I'd like to get the ball rolling on this and use it for the forthcoming mdtraj release. 

I've mulled it over some more and I don't know if an extra tag in the `meta.yaml` file is the right thing to do. Primarily because the label is not a property of the recipe.

**Alternative A:** Make every package upload to a "release candidate" label and move it to the main label as appropriate. Pro: consistent QA, simple logic in this repository. Con: an extra click to move to main label, might by overkill for some packages

**Alternative B:** Have a separate branch in `omnia-md/conda-recipes`. If you pull request your update into that branch, it will upload as release candidate label. Pro: minimal code change, lets recipe authors pick what they want. Con: I think you'd have to then merge your changes back into master so the branches don't get out of sync

**Comment by peastman** [comment]
B sounds like a lot more work than A.  If A really only requires one extra click, that seems more like a pro, not a con.

**Comment by mpharrigan** [comment]
@jchodera do you have any thoughts on pushing *all* packages to a release candidate label first

**Comment by jchodera** [comment]
I'd be willing to give Plan A a shot!  I think you said the magic words with "consistent QA, simple logic".

**Comment by jchodera** [comment]
Do you want to take a stab at implementing these changes into `conda-build-all`?

Also, what do we call the label?  `rc`?  `release-candidate`?  `pre`?

**Comment by jchodera** [comment]
I'd love to also switch the `-dev` package builds over to pushing to a `dev`, `travis`, or `master` label.  I can't tell you how many times weird apparent bugs are just due to someone having installed `packagename` and `packagename-dev` at the same time.  That doesn't require any changes to `conda-build-all`---just us to agree on what label and version numbering scheme to use.

**Comment by mpharrigan** [comment]
Yep! I can make a PR for the changes

If I understand correctly, this scheme is different than the `pre` label. I'm slightly partial to `rc`.

**Comment by mpharrigan** [comment]
I think you'd need some slight changes to `conda-build-all` for the dev recipes to go there, but that sounds like a decent use of these labels as well

**Comment by mpharrigan** [comment]
(I made those slight changes in #509. You'll need to add `--dev` to the travis.yml for the dev recipes repo)

**Comment by mpharrigan** [comment]
(I made those slight changes in #509. You'll need to add `--dev` to the travis.yml for the dev recipes repo)

**Comment by jchodera** [comment]
Thanks! See comments on the PR. I think this could be simplified to just have a single `--label [labelname]` flag, where we can just specify the appropriate default label in `.travis.yml` depending on what the default should be.  The help string could emit our recommendations (`rc` or `dev`).

**Comment by jchodera** [comment]
Looks like we have our first unanticipated problem: `conda-build-all` doesn't find `mdtraj` in the `omnia` channel, so it keeps trying to build the latest release every time, causing travis to time out:
https://travis-ci.org/omnia-md/conda-recipes/jobs/127603893

We need to modify `conda-build-all` to *also* check the `rc` labels.

@mpharrigan : Can you take a stab at this?

**Comment by mpharrigan** [comment]
Stabbed in #515

**Comment by jchodera** [comment]
Also, we just fucked up a bunch of recipes in https://github.com/omnia/conda-dev-recipes because I forgot to add a flag to send those to the `main` channel.

**Comment by jchodera** [comment]
I guess it's time to switch to using the `dev` channel for dev builds, but we have to switch *everything* over or all the travis builds for everything will be broken until we do.  I wonder if we want to dive in and do that now, or do it more gradually (after adding in a `--main` or `--label [labelname]` flag)

**Comment by mpharrigan** [comment]
I would have expected the upload to add a new package so there are both `main` packages (from yesterday) and `rc` packages (from today). But it looks like it overwrites based on version string only.

What's your strategy for transitioning from a scheme where dev packages are named differently to using the dev channel? The nightly builds currently have version strings set to `0.0.0`. I can't imagine that these will *ever* get installed over the non-dev counterparts if someone has the `omnia` channel in their `condarc` file

**Comment by jchodera** [comment]
> I would have expected the upload to add a new package so there are both
main packages (from yesterday) and rc packages (from today). But it looks
like it overwrites based on version string only.

Yikes. We now have the problem that we can never update the build number of
a recipe or else it will knock the package back to 'rc' status and wipe out
the 'main' release. We now have to prohibit build number updates, and only
allow version number increments even if the code version hasn't changed.
Hopefully the use of release candidates eliminates the need for this,
though.

> What's your strategy for transitioning from a scheme where dev packages
are named differently to using the dev channel? The nightly builds
currently have version strings set to 0.0.0. I can't imagine that these
will ever get installed over the non-dev counterparts if someone has the
omnia channel in their condarc file

Currently, developers can cherry-pick whether they want to use the dev or
release versions of various packages for testing. It would be great to
preserve the ability to do that, which would seem to require us adding both
labels to the conda channels in travis.

If we keep the dev version numbers at 0.0.0, it will (hopefully!) guarantee
you will only get the dev version if you ask for this version number.
Otherwise, developers can use the latest release or pin to a specific
version number.

We are still trying to figure out how dev recipes should specify
dependencies. These things only work well of they don't require conflicting
dependencies---that means that not pinning version numbers helps ensure
conflicts don't arise. We have most recently been using dev packages for
any omnia dependencies to figure out when upstream changes might break our
code, but not all packages (eg mdtraj) produce dev versions. If we pin
version numbers, we make sure we can test against the versions we will use
at release, but this also runs the risk of conflicting dependencies.

**Comment by mpharrigan** [comment]
> Yikes. We now have the problem that we can never update the build number of a recipe or else it will knock the package back to 'rc' status and wipe out the 'main' release. We now have to prohibit build number updates, and only allow version number increments even if the code version hasn't changed. Hopefully the use of release candidates eliminates the need for this, though.

Actually we don't have any evidence whether build number increments only will knock it to `rc` status. Can we do an experiment?

**Comment by mpharrigan** [comment]
> If we keep the dev version numbers at 0.0.0, it will (hopefully!) guarantee you will only get the dev version if you ask for this version number. Otherwise, developers can use the latest release or pin to a specific version number.

Got it. So people who want the dev package will say `conda install -c omnia/label/dev openmm==0.0.0` I suspect doing `conda update --all` or `conda update openmm` after that will switch to the latest (non-dev) release package

**Comment by mpharrigan** [comment]
doing an experiment here: 

https://anaconda.org/mpharrigan/left-pad/

**Comment by mpharrigan** [comment]
1. upload to rc label
2. move to main label
3. `conda install -c mpharrigan left-pad`
4. bump version number, rebuild with `conda-build-all` and upload
5. **verify that build 0 are still there under the main label**. The build 1 packages are under the rc label

So we're good w.r.t. build number

**Comment by mpharrigan** [comment]
Second experiment

1. change version to 0.0.0
2. build with `conda-build-all --upload mpharrigan --force --dev`
3. `conda uninstall left-pad` from before
4. add channel `mpharrigan` to my condarc
5. verify `conda install left-pad` pulls the main channel, 0.0.3 build 0 but don't install
6. 'conda install -c mpharrigan/label/dev left-pad` **This still gets 0.0.3 **
7. `conda install -c mpharrigan/label/dev left-pad==0.0.0` gets the "dev" version. Install
8. `conda update left-pad` will remove the dev package and install 0.0.3

**Comment by mpharrigan** [comment]
Whoops didn't mean to close this with #515

**Comment by davidlmobley** [comment]
So, any more headway here?

**Comment by mpharrigan** [comment]
Quick fix: move nightly builds to "main" channel by hand. Disable nightly builds until long term fix:

Long term migration: use `--dev` flag and remove `-dev` suffix when building dev packages. Change recipes to require `packagename==0.0.0` instead of `packagename-dev` and add the dev label to the conda search path

**Comment by jchodera** [comment]
Not during my seven hours of meetings today.

Just getting home and will start working on a fix ASAP.

**Comment by jchodera** [comment]
> Quick fix: move nightly builds to "main" channel by hand. Disable nightly builds until long term fix:

Looks like there's no way to use the UI to move `rc` packages to `main` by hand if no packages are on the `main` channel:
https://anaconda.org/omnia/openmm-dev/files

Also, the command-line `anaconda` interface doesn't seem to support changing labels for a single package: http://docs.anaconda.org/using.html#UploadingPackagesToAnOrganization

**Comment by jchodera** [comment]
I think we just need to add a `--labels [labelname]` flag and use that.

**Comment by jchodera** [comment]
I was able to download and then reupload a package to `main`, then move them all over by hand.

**Comment by mpharrigan** [comment]
> Looks like there's no way to use the UI to move rc packages to main by hand if no packages are on the main channel:

You can't use the "move" dropdown, but you can click the "edit labels" button on an individual package. Then the move dropdown will become available
