### ISSUE TITLE
Info Anaconda

### ISSUE THREAD

**Issue by nividic** [omnia-md/conda-recipes#495]
Hi there,

I would like to upload the lomap package on Omnia. The package helps to plan in advance relative free energy calculations. I’m not very familiar with anaconda and I have some questions. I was able to upload my package on my anaconda channel with all the non standard packages that it depends on. In order to make my package working with the Omnia channel I need to upload my conda recipe by using github. My question is: what else do I need to do? If in the Omnia channel I need other non-standard packages how can I upload them?   

Cheers,

Dr. Gaetano Calabro’
Postdoctoral Research Fellow
Department of Pharmaceutical Sciences
3110 Natural Sciences I
University of California, Irvine
Irvine, CA 92697

**Comment by jchodera** [comment]
Hi @nividic.

The way things work here is that you 
1. Fork this `conda-recipes` repo
2. Add your conda recipe for building `lomap` in a subdirectory called `lomap`. There are plenty of other recipes to use as examples.
3. Open a pull request to merge your branch into this master repo.
4. It will automatically be tested to make sure it compiles.
5. We will discuss the recipe and give suggestions about how to fix any issues.
6. The recipe will be merged and our automated build framework will build and deploy the packages to the `omnia` anaconda channels.

**Comment by nividic** [comment]
I did it,

Thanks for your help,

Gaetano
