### ISSUE TITLE
RDKit build in Omnia causing problems; why is it here?

### ISSUE THREAD

**Issue by davidlmobley** [omnia-md/conda-recipes#512]
@nividic will post full details, but the RDKit build here is broken and leads to a library issue with boost when we try to use it in a fresh `conda` test environment.

A larger question, though, (since we're new to this) is: why is RDKit (now an outdated version) included here at all? It seems as though `conda` doesn't allow channels to be specified in recipes, so this is the only way to make it `conda`-installable without requiring the user to add another channel aside from `omnia`. Is that correct? 

Obviously we could try to fix the RDKit build here, but we're trying to understand whether there is a better way that we're missing...? Maintaining our own RDKit recipe/build seems cumbersome when it is not our software.

**Comment by nividic** [comment]
I was trying to make to work my lomap package with the omnia channel and I found the following problem with the RDkit package:

In a fresh installation of miniconda I create a new environment  requiring the installation of rdkit from the omnia channel. After activating the new environment I tried to run python importing the module Chem from rdkit (from rdkit import Chem) and as error was raised:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gac/local/miniconda2/envs/gactest/lib/python2.7/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import rdBase
ImportError: libboost_python.so.1.59.0: cannot open shared object file: No such file or directory


The installed version of boost was 1.60 from the default conda channel. I also tried to install boot from omnia (version 1.58) with the same result. Can someone help with this?

Thanks

Can someone help with this please

**Comment by jchodera** [comment]
If you look at [the GitHub page](https://github.com/omnia-md/conda-recipes/tree/master/rdkit) you can see that @rmcgibbo added the `rdkit` recipe.

**Comment by nividic** [comment]
I'm sorry, I fixed the problem requiring the installation of boost=1.59. However, in the ominia rdkit recipe it should be specified that the omina version works just with this boost release. 

Thanks

**Comment by jchodera** [comment]
Are you on `linux` or `osx`?

**Comment by nividic** [comment]
I was using Linux ubuntu

**Comment by davidlmobley** [comment]
@jchodera - we're still very interested in the overall answer to this question when you have a moment:

> A larger question, though, (since we're new to this) is: why is RDKit (now an outdated version) included here at all? It seems as though conda doesn't allow channels to be specified in recipes, so this is the only way to make it conda-installable without requiring the user to add another channel aside from omnia. Is that correct?

**Comment by rmcgibbo** [comment]
IIRC @rbharath and I added it because, like all of the other dependencies in omnia, it was necessary for some project and wasn't included in the base Anaconda channels.

**Comment by davidlmobley** [comment]
@rmcgibbo - at some level I get that. I'm still just a newb to this world though so I'm just after clarification: There is no way to make a conda recipe specify a channel to install from, so the only way to include software that isn't in the base Anaconda channels in a conda recipe is to include it in your channel? It strikes me as really odd since it would seem to lead to a proliferation of other channels which have to duplicate things (i.e. everyone whose software needs RDKit and wants to distribute it via conda would have to do the same thing we're doing...).

**Comment by rmcgibbo** [comment]
Right. When you write a recipe, you cannot say what channel a dependency will come from --- dependencies are specified by package name (and optional a version number constraint), but not by channel. This is probably for the best, IMO, because not all of the conda channels are so diligent about proper portable linux binaries or Windows / OS X support anyways.

Unfortunately this stuff (facilitating easy binary installations for users) is somewhat nontrivial in the general case, and it's not my top priority anymore. If others are interested, it might not be a bad idea to see about moving more of this channel/infra into something with a wider community backing, like [conda-forge](https://www.continuum.io/blog/developer-blog/community-conda-forge).

**Comment by jchodera** [comment]
I've been reading along in the https://www.continuum.io/blog/developer-blog/community-conda-forge discussion, but I think it will be a little while before we can jump over to that model (mainly regarding CUDA/OpenCL support).  There are lots and lots of great aspects of that projects we don't have that would solve issues like this (like designated package maintainers).

**Comment by jchodera** [comment]
Another way around the dependency issue is to just copy the more recent packages to our channel and dump the recipe.  I'm happy to do this if you think it would help.

**Comment by rmcgibbo** [comment]
> Another way around the dependency issue is to just copy the more recent packages to our channel and dump the recipe. I'm happy to do this if you think it would help.

You have to be careful with boost though -- it might depend on an ABI incompatible version of boost from the one in our channel.

I think boost is now in the main channel (it wasn't before), so probably we should get rid of our version of boost and peg things to that.

> but I think it will be a little while before we can jump over to that model (mainly regarding CUDA/OpenCL support)

You're probably right, but it would be *possible* to move over everything other than OpenMM and its downstreams.

**Comment by davidlmobley** [comment]
I think mostly this can be closed since I now understand the issues. But, should we create separate issues for:
- remove our version of boost and peg things to main version of boost
- designate package maintainers for the various different things we've had to pull into this channel

**Comment by jchodera** [comment]
Please create those issues!
