### ISSUE TITLE
Need a way to force builds in conda-build-all

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#561]
Now that we seem to have eliminated `--check-against`, we need a way to ensure that all packages are listed by [`required_builds()`](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L296) if we use the `--force` flag to ensure the recipes are rebuilt.

**Comment by mpharrigan** [comment]
Why? Can't you increment build number if you want to rebuild a package

**Comment by rmcgibbo** [comment]
Why do you say that check_against was eliminated? I still see it in the code.

**Comment by jchodera** [comment]
> Why? Can't you increment build number if you want to rebuild a package

Automated forced rebuilds of the `dev` package are needed by https://github.com/omnia-md/conda-dev-recipes for nightly builds of `openmm` to be uploaded to the `dev` label.

> Why do you say that check_against was eliminated? I still see it in the code.

It doesn't actually do anything now.

**Comment by jchodera** [comment]
Specifically, it doesn't do anything now because packages are eliminated from the build list if [they already exist on `anaconda.org`](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L336-L342).

**Comment by mpharrigan** [comment]
I'm so confused. There's clearly a `force` parameter used there

**Comment by mpharrigan** [comment]
Oh lol you added that in #564

**Comment by jchodera** [comment]
Nine hours ahead of you (here in Berlin).

This is working now, I think!
