### ISSUE TITLE
mingwpy: what do we do for [win and py35] support?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#569]
Our current [`mingwpy` recipe](https://github.com/omnia-md/conda-recipes/tree/master/mingwpy) skips `py35` on `win`, but we have deprecated `py34` on `win`, meaning we can no longer build any packages that depend on `mingwpy` for `win`.

[`conda-force` provides `mingwpy` for `py35` `win`](https://anaconda.org/conda-forge/mingwpy/files). Can we use this instead?

**Comment by rmcgibbo** [comment]
I recommend checking with https://mingwpy.github.io and their forums. Py35 uses vs2015 on win which has a totally different ABI and runtime link design. The last time I was involved, mingw did not support it yet.

Why did we deprecate py34 on win?

**Comment by rmcgibbo** [comment]
Is it accurate that we have deprecated py34 on Windows? There's no issue about it, and it's still in the Appveyor yaml.

**Comment by jchodera** [comment]
My bad---I just read the appveyor test failures incorrectly. We're still [building against py34 on `win`](https://github.com/omnia-md/conda-recipes/blob/master/appveyor.yml).

I'll punt on any changes then.

**Comment by jchodera** [comment]
And thanks!
