### ISSUE TITLE
Travis update to osx images

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#605]
Looks like travis has updated their `osx` images from 10.9 to 10.11 on 4 Oct 2016:
https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/

cc: https://github.com/omnia-md/conda-recipes/pull/603#issuecomment-251468284

I'll see if I can somehow minimize the damage here.

**Comment by jchodera** [comment]
For reference, the [`osx_image` choices are documented here](https://docs.travis-ci.com/user/languages/objective-c/).

**Comment by mpharrigan** [comment]
(Warning: naivety ahead). Shouldn't a minor version bump be of minimal impact?

**Comment by swails** [comment]
What version bump are you talking about?

**Comment by mpharrigan** [comment]
xcode 6.1 -> xcode 6.4

**Comment by swails** [comment]
This is what Wikipedia says: https://en.wikipedia.org/wiki/Xcode#Xcode_5.0_-_6.x_.28since_arm64_support.29

iOS and OS X versions are a moving target (as are Swift versions -- Swift syntax is still changing, frustratingly).  So while the impact is smaller than going all the way to Xcode 7, it's not always "small" (or it would quickly lose utility).

**Comment by jchodera** [comment]
> xcode 6.1 -> xcode 6.4

I think this should be OK, but wanted to have more time to explore it. (I'm in the middle of traveling right now.)

Just merged #606, which restores the old behavior until 31 Oct 2016. 

If someone wants to try a PR that updates to `xcode 6.4` and debug any issues that might pop up, that would be awesome!
