### ISSUE TITLE
MDTraj on conda-forge

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#634]
Conda forge has some good infrastructure set up for community-maintained conda packages. https://conda-forge.github.io/

@rmcgibbo already has mdtraj set up to be built there. For our forthcoming release of 1.8, I plan on using the conda-forge machinery to build our official binaries and copy them over to the omnia channel. The omnia machinery won't be used to build the binaries

**Comment by mpharrigan** [comment]
crossref https://github.com/mdtraj/mdtraj/issues/1196

**Comment by jchodera** [comment]
I'm very interested in trying to migrate omnia over to conda-forge, and I think there is a path to do this with openmm as well. 

Do you foresee any issues with compatibility if you build on conda-forge? Which range of glibc libraries will the compiled code be compatible with, for example, and will that match the rest of omnia (which is compiled with CentOS 5.x)?

**Comment by rmcgibbo** [comment]
The forward compatibility is fine, but not the backward compatibility, so these binaries will not be usable on CentOS 5.

**Comment by rmcgibbo** [comment]
The only circimstance I can think of in which this might matter (other than for users who are still using EOL-ed linuxes) is that if one of the omnia project's build systems needed to use MDTraj's C/C++ code _at build time_ to compute some distances or RMSDs, it would break.

I can't think of any projects whose setup.py script requires running RMSD calculations though.

**Comment by jchodera** [comment]
Sounds reasonable.

We should discuss potential migration to conda-forge in the next omnia call.

I don't see the harm in copying over the package to the omnia channel, but
I haven't thought through all the potential ramifications yet.

**Comment by mpharrigan** [comment]
For those keeping score at home, this turned out to be easy.

https://docs.continuum.io/anaconda-cloud/cli#copy

```bash
$ anaconda login
$ anaconda copy conda-forge/mdtraj/1.8.0 --to-owner omnia
Using Anaconda API: https://api.anaconda.org
Copied file: linux-64/mdtraj-1.8.0-np110py27_0.tar.bz2
Copied file: linux-64/mdtraj-1.8.0-np110py34_0.tar.bz2
Copied file: linux-64/mdtraj-1.8.0-np110py35_0.tar.bz2
Copied file: linux-64/mdtraj-1.8.0-np111py27_0.tar.bz2
Copied file: linux-64/mdtraj-1.8.0-np111py34_0.tar.bz2
Copied file: linux-64/mdtraj-1.8.0-np111py35_0.tar.bz2
Copied file: osx-64/mdtraj-1.8.0-np110py27_0.tar.bz2
Copied file: osx-64/mdtraj-1.8.0-np110py34_0.tar.bz2
Copied file: osx-64/mdtraj-1.8.0-np110py35_0.tar.bz2
Copied file: osx-64/mdtraj-1.8.0-np111py27_0.tar.bz2
Copied file: osx-64/mdtraj-1.8.0-np111py34_0.tar.bz2
Copied file: osx-64/mdtraj-1.8.0-np111py35_0.tar.bz2
Copied file: win-32/mdtraj-1.8.0-np110py35_0.tar.bz2
Copied file: win-32/mdtraj-1.8.0-np111py35_0.tar.bz2
Copied file: win-64/mdtraj-1.8.0-np110py35_0.tar.bz2
Copied file: win-64/mdtraj-1.8.0-np111py35_0.tar.bz2
Copied 16 files
```

**Comment by jchodera** [comment]
Yay! It works now!

This was not easy when I tried it a few months back...

**Comment by mpharrigan** [comment]
Glad you didn't tell me that earlier! :)
