### ISSUE TITLE
smarty won't conda install in py35

### ISSUE THREAD

**Issue by davidlmobley** [omnia-md/conda-recipes#649]
@jchodera - I just attempted to conda install `smarty` in py35 and I get an error that it is python3.5 is "in conflict" with smarty.

**Comment by mpharrigan** [comment]
Looks like it explicitly isn't being build on py3 https://github.com/omnia-md/conda-recipes/blob/master/smarty/meta.yaml#L12

**Comment by davidlmobley** [comment]
@jchodera - any comments on why you set it up this way? Presumably we should adjust it not to skip py3?

**Comment by jchodera** [comment]
I suspect that's left over from when your students were checking in non-python-3 compliant code and [we needed to cut a release](https://github.com/omnia-md/conda-recipes/pull/570).

I believe I fixed that and [python 3.x tests are passing now](https://travis-ci.org/open-forcefield-group/smarty). Can you submit a PR to remove the skip directive?

**Comment by davidlmobley** [comment]
Done in #653
