### ISSUE TITLE
Newest version of conda breaks recipes

### ISSUE THREAD

**Issue by jlmaccal** [omnia-md/conda-recipes#669]
The new `4.3.4` version of `conda` breaks the old `2.0.1` version of `conda-build` that we are using. We also use some non-public APIs from `conda-build`, which means that `conda-build-all` breaks if we update `conda-build`.

I'm working to sort this out...

**Comment by jlmaccal** [comment]
Also, the `|| true` on this [line](https://github.com/omnia-md/conda-recipes/blob/master/devtools/docker-build.sh#L17) makes the build appear to pass, even when `conda-build-all` fails.

**Comment by jchodera** [comment]
Thanks for digging into this!

**Comment by jchodera** [comment]
cc: #672

**Comment by Lnaden** [comment]
What do we have here that requires `conda-build` 2.0.1?

**Comment by jchodera** [comment]
This was fixed by #671
