### ISSUE TITLE
Rebuild ambermini16?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#672]
cc: https://github.com/choderalab/perses/issues/314

**Comment by jchodera** [comment]
Tagging @Lnaden and @pgrinaway

**Comment by Lnaden** [comment]
Im not sure what rebuilding this will do. Ambermini isn't pinned to a conda-build version and is running off the `conda-build` that is a part of `conda-recipes`.

**Comment by Lnaden** [comment]
Fixed by #674
