### ISSUE TITLE
Numpy 1.12 released

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/conda-recipes#678]
We should build packages

**Comment by Lnaden** [comment]
Based on the [patch notes](https://github.com/numpy/numpy/blob/master/doc/release/1.12.0-notes.rst) Python 2.6 support was dropped. Although this should not affect any of our projects, it _might_ affect the Holy Build Box since CentOS 5's base Python version is 2.6, which cannot be replaced as `yum` and some other things require it.

cc @jchodera

**Comment by mpharrigan** [comment]
>  it might affect the Holy Build Box since CentOS 5's base Python version is 2.6, which cannot be replaced as yum and some other things require it.

No, I don't think so. The system python is completely unrelated to our build system. For reference, the centos 5 system python is version 2.4

**Comment by Lnaden** [comment]
I appear to have mis-remembered. Still good to know though!

**Comment by jchodera** [comment]
Can we just add it [here](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L104) without removing older numpy builds for the moment?

**Comment by jchodera** [comment]
Numpy 1.12 is not yet available on anaconda:
https://anaconda.org/anaconda/numpy/files

**Comment by jchodera** [comment]
It *is* available on [conda-forge](https://anaconda.org/conda-forge/numpy/files), which complicates things.

**Comment by Lnaden** [comment]
There is another complication in that it does not look like the conda-forge version compiles windows builds. We may have to rely on just what is available through the main anaconda channel if we can't get windows builds, don't want to leave users behind.

**Comment by marscher** [comment]
It is now available in the defaults channel, shall I enable the build, like suggested?

**Comment by marscher** [comment]
Pythen 3.4 and Numpy 1.12 are not built by Anaconda.

**Comment by jchodera** [comment]
Thanks for taking a stab at this!
