### ISSUE TITLE
glibc issue with fftw3f

### ISSUE THREAD

**Issue by kyleabeauchamp** [omnia-md/conda-recipes#68]
I was doing a `./conda-build-all openmm` in my Centos VM and I saw this:

```
[ 67%] Built target TestVectorize
Scanning dependencies of target TestReferenceDrudeForce
[ 67%] /home/vagrant/miniconda/envs/_build/lib/libfftw3f.so: undefined reference to `memcpy@GLIBC_2.14'
/home/vagrant/miniconda/envs/_build/lib/libfftw3f.so: undefined reference to `__log_finite@GLIBC_2.15'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe I'm getting my `( fftw3f:               3.3.3-1)` from binstar (https://binstar.org/omnia/fftw3f/files).  Any idea on the provenance of that binary?  E.g. was it built from our Ubuntu 12.04 boxes?  We might want to disable uploading those to binstar (or use a separate channel?), as we know those builds likely have glibc incompatabilties and should not be broadly deployed.

**Comment by kyleabeauchamp** [comment]
I've disabled that file on the main channel and that seems to fix the problem--conda then builds `fftw3f` from the recipe before building openmm.

**Comment by jchodera** [comment]
> Any idea on the provenance of that binary? E.g. was it built from our Ubuntu 12.04 boxes?

That very well may have been my fault.

If you're building in the VM, can you upload a fixed version of `fftw3f` to your `omnia1_beta` channel?

**Comment by rmcgibbo** [comment]
> I've disabled that file on the main channel and that seems to fix the problem--conda then builds fftw3f from the recipe before building openmm.

This kills other stuff. e.g. the Travis-CI build of the docs for mdtraj uses `conda install openmm`, which lists "fftw3f" as a requirement with no available installation candidate, since it's looking on the main channel.

**Comment by kyleabeauchamp** [comment]
I think this is solved
