### ISSUE TITLE
Remove OpenBabel 2015.09 from omnia channel to fix conda issue

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/conda-recipes#681]
OpenBabel's version number scheme was changed from `YEAR.MO` (i.e. `2015.09`) to `X.Y.Z` (`2.4.0`) back in f11096c. However, that means that conda considers 2015 > 2 so trying to install OpenBabel without pinning it to a specific version will always result in grabbing the old compiled version. Because this was compiled with `conda-build < 2.0.0` this causes issues like in #677

Software depending on OpenBabel can pin the version to the `2.4.0` and that will temporarily fix this problem once, but we would have to do this any time OpenBabel changes, and it still does not solve the problem that all OpenBabel installs will always be on the older version. 

I propose actually removing the `2015.09` version from the `omnia` channel as it is the identical version to `2.4.0`. This would preserve scientific reproducibility since the identical version would be available, but we would need to make note of this somewhere that `2015.09 == 2.4.0`.

cc @rbharath @jchodera

**Comment by mpharrigan** [comment]
https://www.python.org/dev/peps/pep-0440/#version-epochs

**Comment by Lnaden** [comment]
Good to know. It looks like the `VersionOrder` in conda will actually recognize this, but it will appear on the `omnia` channel as `1!2.4.0` and all subsequent versions will need the epoch number to be registered correctly since no epoch defaults to 0. 

I'll draft a PR for it
