### ISSUE TITLE
Python 3.6 Support

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/conda-recipes#685]
Python 3.6 was officially released in late December. As of 1/23/17, the [official "What's New"](https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-pep498) notes were released. We should consider building against Python 3.6 as well as 3.4 and 3.5.

I did not see anything on the notes which would be show stopper in terms of changes, but the following changes may affect some packages.
* `**kwargs` [ordering is now respected](https://www.python.org/dev/peps/pep-0468/)
* Class Attribute Definition Order is preserved
* Windows filesystem and console encoding is UTF-8
* There are a few [deprecated methods](https://docs.python.org/3.6/whatsnew/3.6.html#deprecated) worth looking over.

There may of course be other things that break, but I think its worth discussing to eventually start support.

**Comment by mpharrigan** [comment]
cc #663

**Comment by Lnaden** [comment]
Ah, missed that. Duplicate then
