### ISSUE TITLE
cvxpy is not python 3.3 or 3.4 compatible

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#69]
The `conda-build-all` script produces lots of errors when trying to build with python 3.3 or 3.4.

Is this OK, @rmcgibbo?  Do any of the tools that require it need to work with python 3.3 or 3.4?

**Comment by rmcgibbo** [comment]
Yes, it's fine. I contributed a port to py3k to `cvxpy`; it's in `master`,
but hasn't been released yet. `cvxpy` is not a "hard" dependency for
msmbuilder -- it's used for only a single type of model, not throughout the
codebase. The code will work fine (obvously without that feature) if
`cvxpy` is not available.

**Comment by jchodera** [comment]
OK!  I wonder if we need some way of encoding which packages are supposed to work with which versions of python if we're going to have a mixture of packages that do and do not support python 3.x.

**Comment by rmcgibbo** [comment]
Yeah, +1.

**Comment by jchodera** [comment]
Created #76 for that.
