### ISSUE TITLE
parmed md5 mismatch

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#699]
Downloading https://github.com/ParmEd/ParmEd/archive/2.7.1.tar.gz
Success
MD5 mismatch: 'd19c063087de4d06652cf0ee3fcd5014' != 'f8387c2dc16ba627d2a3fcbf1909b48f'

Please note, that the Github archives are created on the fly and it is likely that it produces different outputs (eg. they change the compression flags etc.).

**Comment by jchodera** [comment]
Is this a failure of the parmed recipe to build?
