### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#702]
I'm starting this thread to address some issues that come up in attempting to add python 3.6 support.

The first one, noted [here](https://travis-ci.org/omnia-md/conda-recipes/jobs/199316385#L3804-L3857), is this issue with `msmtools`:
```
BUILD START: msmtools-1.2-np110py36_0
    (actual version deferred until further download or env creation)
Traceback (most recent call last):
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 1480, in build_tree
    config=config)
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 945, in build
    create_env(config.build_prefix, specs, config=config)
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 730, in create_env
    raise
  File "/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda/lib/python3.5/site-packages/conda_build/utils.py", line 523, in path_prepended
    yield
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 685, in create_env
    warn_on_old_conda_build(index=index)
  File "/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda/lib/python3.5/site-packages/conda_build/utils.py", line 109, in try_acquire_locks
    yield
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 676, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/anaconda/lib/python3.5/site-packages/conda/plan.py", line 487, in install_actions
    update_deps, pinned)
  File "/anaconda/lib/python3.5/site-packages/conda/plan.py", line 662, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/anaconda/lib/python3.5/site-packages/conda/resolve.py", line 815, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/anaconda/lib/python3.5/site-packages/conda/resolve.py", line 869, in solve
    self.find_conflicts(specs)
  File "/anaconda/lib/python3.5/site-packages/conda/resolve.py", line 377, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.10* -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/anaconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/anaconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/anaconda/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 1523, in build_tree
    .format(recipe, e.pkgs) + "\n\n" + extra_help)
AttributeError: 'UnsatisfiableError' object has no attribute 'pkgs'
ERROR: File does not exist: /anaconda/conda-bld/linux-64/msmtools-1.2-np110py36_0.tar.bz2
Package failed to build (return code 1); will not upload.
```
It appears that the `anaconda` channel only provides numpy `1.11` with `python 3.6`, so I don't think this is an actual problem. Posting it here just in case.

**Comment by jchodera** [comment]
It appears that `msmtools` *was* built for `python 3.6` and `numpy 1.11`, so I just retriggered the build to finish building other packages: https://anaconda.org/omnia/msmtools/files

**Comment by marscher** [comment]
We need to adopt the build matrix/conda-build-all for the situation we don't have numpy 1.10 for py36.

**Comment by marscher** [comment]
I dont really understand this behaviour. The build for pyemma py3.6 np111 succeeds, but the testing (just the creation of the environment) fails with this message:
```
TEST START: pyemma-2.3.1-np111py36_0
Deleting work directory, /anaconda/conda-bld/pyemma_1486496181181/work/pyEMMA-2.3.1
Can't build /io/pyemma due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - pyemma 2.3.1 np111py36_0
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by marscher** [comment]
If I install all the dependencies of pyemma locally in a py36 env and do a local git install, everything succeeds. So it is unclear why the package is in conflict with itself...

**Comment by marscher** [comment]
still failing for py36:

´´´[conda-build-all] Error: one or more packages failed to build (osx-64)
  gpy-0.8.8.post1-py36_0.tar.bz2
  numdifftools-0.9.14-py36_0.tar.bz2
  rdkit-2015.09.1-py36_2.tar.bz2
  pdbfixer-1.4-py36_0.tar.bz2
  openmmtools-0.8.3-py36_1.tar.bz2
  alchemy-1.2.3-py36_0.tar.bz2
  openmoltools-0.7.4-py36_0.tar.bz2
  sams-0.1.1-py36_0.tar.bz2
  yank-0.15.0-py36_0.tar.bz2
  solvationtoolkit-0.4.2-py36_0.tar.bz2
```

**Comment by jchodera** [comment]
Does it look like these are generic python 3.x issues or specific python 3.6 issues?

**Comment by marscher** [comment]
On 20.02.2017 00:44, John Chodera wrote:
> Does it look like these are generic python 3.x issues or specific python
> 3.6 issues?
Not generic, but most of the failures should be due to missing Py3.6 
dependencies (haven' looked in the recipes, but OpenMM showed up for 
quite a few packages as missing for Py36).

**Comment by jchodera** [comment]
So `openmm` isn't being built for py36? Or do we just have to trigger travis builds a few more times to build all the dependencies?

**Comment by marscher** [comment]
On 20.02.2017 00:52, John Chodera wrote:
> So |openmm| isn't being built for py36? Or do we just have to trigger
> travis builds a few more times to build all the dependencies?
The posted list didn't change for a couple of PRs, so I think you have 
to enable/build OpenMM manually. Maybe a dependency problem it self.

To debug locally, try to create an environment containing the 
build/runtime dependencies of OpenMM for python=3.6.

**Comment by Lnaden** [comment]
Is there a reason to need `sphinxcontrib-autodoc_doxygen` pinned to version `sphinx==1.3.1`? That appears to be the main hold up to OpenMM on Python 3.6? If we unpin the `sphinx` version, or at least go to `1.5.1`, we should be able to get the Python 3.6 support going.

@jchodera or @peastman might know if there is a reason.

**Comment by peastman** [comment]
That library was created by @rmcgibbo, so he's the one to ask.

**Comment by rmcgibbo** [comment]
The tests for the HEAD of sphinxcontrib-autodoc_doxygen are running with Sphinx 1.5, so that's a combo that has been validated. `https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/blob/master/requirements.txt`

**Comment by Lnaden** [comment]
Great! I'll try unpinning and see if I can get OpenMM to build

**Comment by Lnaden** [comment]
So the OpenMM builds are now going for Python 3.6, but based on the [files here] (https://anaconda.org/omnia/openmm/files), the linux Python 3.6 build got sent to the `dev` label whereas the rest of the 7.1.0rc1 builds are on the `main` label. Any idea why that happened?

**Comment by peastman** [comment]
OpenMM builds never get sent to the `main` label automatically.  We move them there by hand once they've been tested.

**Comment by Lnaden** [comment]
Ah. Good to know. Thank you!

**Comment by Lnaden** [comment]
Ha ha! We are Python 3.6 stable save a few packages that I can't figure out

* `cvxopt` libgfortran cannot be found. We could remove the `-lgfortran` flag but I don't know if that is what we want.
* `meld-plugin` relies on the `openmm-dev` package which might be a legacy thing from the first time it was built.
* `lomap` PyQt4 error which may [not actually be our fault](https://github.com/ContinuumIO/anaconda-issues/issues/1068)

I think everything else is waiting for OpenMM 7.1 testing on python 3.6 to move to the `main` tag

**Comment by peastman** [comment]
See https://github.com/pandegroup/openmm/issues/1758.

**Comment by cxhernandez** [comment]
What's the status with py36 compatibility so fr? 

We have a [msmbuilder/msmexplorer user](https://github.com/msmexplorer/msmexplorer/issues/77#issuecomment-285539053) who can't install the py36 binaries on macOS even though the [files seem to be available on the omnia channel](https://anaconda.org/omnia/msmexplorer/files).

**Comment by Lnaden** [comment]
I spent last week getting as much as I could uploaded. We still need to test OpenMM on python 3.6 to move a number of the packages.

As to that exact issue, I found the problem and will tag the author.

**Comment by Lnaden** [comment]
Otherwise we should have most of it working.

**Comment by jchodera** [comment]
What's blocking the OpenMM release? Do we just need @peastman to approve the migration from `dev` to `main`?

**Comment by Lnaden** [comment]
We have that conversation on-going at pandegroup/openmm#1758

**Comment by jchodera** [comment]
We now have Python 3.6 support.
