### ISSUE TITLE
Build for pyhmc conda package fails on jenkins osx

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#71]
Might be for source code checkout reasons.

The output:
```
BUILD START: pyhmc-0.1.1-np18py27_0
Fetching package metadata: ....
Solving package specifications: .Cloning into bare repository '/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/conda-bld/git_cache/rmcgibbo_pyhmc.git'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



The following NEW packages will be INSTALLED:

    cython:     0.21.2-py27_0
    numpy:      1.8.2-py27_0 
    openssl:    1.0.1j-4     
    python:     2.7.9-1      
    readline:   6.2-2        
    setuptools: 7.0-py27_0   
    sqlite:     3.8.4.1-0    
    tk:         8.5.15-0     
    zlib:       1.2.7-1      

Linking packages ...
 |                                                                       |   0%
[readline-6.2-2 /Users/jenkins-slave/workspace/conda-omnia-release] |    |  11%
[sqlite-3.8.4.1-0 /Users/jenkins-slave/workspace/conda-omnia-release] |  |  22%
[zlib-1.2.7-1 /Users/jenkins-slave/workspace/conda-omnia-release] |##    |  33%
[openssl-1.0.1j-4 /Users/jenkins-slave/workspace/conda-omnia-release] |  |  44%
[tk-8.5.15-0 /Users/jenkins-slave/workspace/conda-omnia-release] |###    |  55%
[python-2.7.9-1 /Users/jenkins-slave/workspace/conda-omnia-release] |##  |  66%
[cython-0.21.2-py27_0 /Users/jenkins-slave/workspace/conda-omnia-release] ||  77%
[numpy-1.8.2-py27_0 /Users/jenkins-slave/workspace/conda-omnia-release] ||  88%
[setuptools-7.0-py27_0 /Users/jenkins-slave/workspace/conda-omnia-release] || 100%
[      COMPLETE      ] |#################################################| 100%
Removing old work directory
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 272, in execute
    build.build(m, verbose=not args.quiet, post=post)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 310, in build
    source.provide(m.path, m.get_section('source'))
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 236, in provide
    git_source(meta, recipe_dir)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 100, in git_source
    check_call([git, 'clone', '--mirror', git_url, cache_repo_arg], cwd=recipe_dir)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'clone', '--mirror', u'git@github.com:rmcgibbo/pyhmc.git', u'/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/conda-bld/git_cache/rmcgibbo_pyhmc.git']' returned non-zero exit status 128
```

Is this needed for `omnia 1.0`?

**Comment by rmcgibbo** [comment]
Nothing lists this project as a dependency. It's not required for `omnia 1.0`. The reason that `pyhmc` exists here is because it's used in a current PR for msmbuilder.

More generally, looking at the recipe directories here, we have both "omnia" projects, and projects which are included solely because they are requirements of "omnia" projects. When you run `build-all`, you might want to separate these.

**Comment by jchodera** [comment]
> Nothing lists this project as a dependency. It's not required for omnia 1.0. The reason that pyhmc exists here is because it's used in a current PR for msmbuilder.

Thanks!  I've marked this for `omnia 2.0` then so we don't get hung up on issues for the 1.0 release.

> More generally, looking at the recipe directories here, we have both "omnia" projects, and projects which are included solely because they are requirements of "omnia" projects. When you run build-all, you might want to separate these.

Why?  And how would you suggest best doing that?

**Comment by rmcgibbo** [comment]
Have a list of filenames, and only run `cat omnia-projects.txt | xargs | conda-build-all` or something.

**Comment by rmcgibbo** [comment]
Or whatever shell scripting you want.

**Comment by jchodera** [comment]
> Have a list of filenames, and only run cat omnia-projects.txt | xargs | conda-build-all or something.

Sure, we could do this.  But is it really necessary?  

I guess it could be useful to have two lists:
* `projects-release.txt` - all main packages to be built and pushed to the `release` binstar channel; dependencies will be automatically built
* `projects-dev.txt` - all main packages to be built and pushed to the `dev` binstar channel; dependencies will be automatically built

Alternatively, `release` could be named something like `omnia1.0` or something.

**Comment by rmcgibbo** [comment]
Whatever's easiest and get the job done is fine.

**Comment by rmcgibbo** [comment]
We want the release to be on the [`main` channel](http://docs.binstar.org/channels.html), right? That way users who don't configure a custom channel will get the release versions.

**Comment by jchodera** [comment]
That's right.  But because @kyleabeauchamp is currently building the linux stuff by hand, I'm sending the Jenkins-built stuff somewhere else (currently the `jenkins` channel) with the idea that we would move packages over by hand for the official 1.0 release.

**Comment by rmcgibbo** [comment]
I know. I was responding to your previous recommendation of the label `release` or `omnia1.0` for the final channel name of the release version.

**Comment by kyleabeauchamp** [comment]
Or we could just run the script on the omnia 1.0 metapackage.  Wouldn't
that solve this problem automatically?

**Comment by jchodera** [comment]
> Or we could just run the script on the omnia 1.0 metapackage.  Wouldn't that solve this problem automatically?

Good idea! Trying this now.

**Comment by jchodera** [comment]
> Or we could just run the script on the omnia 1.0 metapackage. Wouldn't that solve this problem automatically?

It doesn't look like building the `omnia` metapackage automatically builds the dependencies:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/10/console

My guess is that this is because the dependencies are only specified in the `run:` section of [`meta.yaml`](https://github.com/omnia-md/conda-recipes/blob/master/omnia/meta.yaml), not the `build:` section.
