### ISSUE TITLE
Some Python 3.6 builds are just not compiling

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/conda-recipes#719]
I can't tell what the causes, but it appears as through some of the builds are simply not being staged for Python 3.6. There is no record of them ever being attempted or even considered in the Travis log files, so there is no error to debug.

Most notably is OpenMM, but there is also things like nose-timer on osx. 

The big one is OpenMM which is holding back a number of the other packages from being built on Python 3.6 as well. Is there possibly something going [in the `conda-build-all` code](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L304-L378) which is iterating through the list of Python and NumPy versions and just missing a combination sometimes?

**Comment by jchodera** [comment]
It looks like the logic for skipping some python 3.6 builds must be causing all of them to be skipped.

@marscher : Any ideas?

**Comment by jchodera** [comment]
I think we need to temporarily disable python 3.6 builds until we can figure out what's going on.
