### ISSUE TITLE
nglview uses tag prefix in conda_version field

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#732]
This leads to problems if one uses other channels which provide nglview too, because the same version is treated differently, because of the "different" version.

Can I just change this or will other things brake then? @cxhernandez I think you introduced this, was there any cause to do so?

cc @gph82

**Comment by Lnaden** [comment]
I introduced this change trying to get the Python 3.6 builds to go. I had updated the `meta.yaml` file so that it could get dependencies that were also 3.6 compatible. Feel free to correct the mistake. Worst case scenario, we can pull the incorrect version numbered files off of the `conda` channel to avoid clashes

**Comment by Lnaden** [comment]
Just to make sure, the mistake was `version: "v0.6.2.2"` should be `version: "0.6.2.2"`?

**Comment by marscher** [comment]
On 06.03.2017 22:03, Levi Naden wrote:
> Just to make sure, the mistake was |version: "v0.6.2.2"| should be
> |version: "0.6.2.2"|?
Exactly. I think it was introduced for version 0.5

But we should just increase the build number and correct the version, so 
we wont interfere with older versions/dependents of the package.

**Comment by cxhernandez** [comment]
@marscher: I think it's fine to change back. At the time, there was an issue with how `nglview` interacted with `ipywidgets` but that's since been fixed.

**Comment by marscher** [comment]
Thanks for clarifying @cxhernandez.

**Comment by Lnaden** [comment]
> But we should just increase the build number 

That is a good idea. Do you want to make the PR or I can?

**Comment by marscher** [comment]
On 06.03.2017 22:07, Levi Naden wrote:
>     But we should just increase the build number
>
> That is a good idea. Do you want to make the PR or I can?
Go for it! Thank you :)

**Comment by Lnaden** [comment]
Okay, when that passes the nglview builds I'll get it merged in. Might be a bit since OSX builds are backlogged

**Comment by marscher** [comment]
Thank you for the PR

**Comment by hainm** [comment]
for pure Python-JS package like `nglview`, I would install via `pip` :D.
