### ISSUE TITLE
Builds failing due to conda changes

### ISSUE THREAD

**Issue by jlmaccal** [omnia-md/conda-recipes#735]
I'm not sure if this repo has hit this problem yet, but it will... I use the same `conda-build-all` script to build MELD and we're now getting the following error:

```
Traceback (most recent call last):
  File "/io/devtools/conda-build-all", line 459, in <module>
    sys.exit(main())
  File "/io/devtools/conda-build-all", line 122, in main
    return execute(args, p)
  File "/io/devtools/conda-build-all", line 429, in execute
    to_build = list(required_builds(metadatas, pythons, numpys, channel_urls, verbose=args.verbose, force=args.force))
  File "/io/devtools/conda-build-all", line 331, in required_builds
    bldpkg_path = get_bldpkg_path(m, python, numpy)
  File "/io/devtools/conda-build-all", line 230, in get_bldpkg_path
    cfg.noarch = False
AttributeError: can't set attribute
```

I'm sure this is once again due to some internal change in `conda` or `conda-build`.

I really wonder if it isn't a mistake to roll our own `conda-build-all` script. Issues like this have become annoyingly common, as Continuum hasn't been shy about breaking their APIs. We should investigate if we can use other tools to build and upload these packages, either conda's own tools or something like https://github.com/SciTools/conda-build-all, so that we don't have to waste our efforts sorting out nonsense like this.

**Comment by Lnaden** [comment]
So far we are not seeing the problem. Although I would fully put it on `conda` or `conda-build` with how often they break their API.

We are eventually going to go to `conda-forge` where hopefully we don't have to worry about building this all ourselves. At least thats how I understand the system should work.

**Comment by jlmaccal** [comment]
> So far we are not seeing the problem

I think that's just because the build is failing at an earlier stage.

**Comment by Lnaden** [comment]
Yeah, I am seeing the problem now. And it is because of how `conda-build` changed their `noarch` setting specifically. I'll see if I can figure out why and/or find a less time consuming answer.

**Comment by Lnaden** [comment]
Here is the compare I am looking at https://github.com/conda/conda-build/compare/2.1.5...2.1.6

**Comment by Lnaden** [comment]
Do we even need that particular check anymore? I have done some small tests and cannot reach the code to set the flag to `True`, its and it starts out as `False` by default, this is in both 2.1.5 and 2.1.6

**Comment by jlmaccal** [comment]
> Do we even need that particular check anymore? I have done some small tests and cannot reach the code to set the flag to True, its and it starts out as False by default, this is in both 2.1.5 and 2.1.6
> 
> 

I honestly don’t know. It looks like this is only involved when building `noarch` packages, so unless the tests you’ve run include such a package, I don’t think you would see any issue.

My frustration with the current approach is that we’re regularly having to dig through the guts of `conda` or `conda-build`, which none of us know well.

**Comment by jchodera** [comment]
We're running into this in [`conda-dev-recipes`](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/209623395#L367-L379).

**Comment by Lnaden** [comment]
Yes, thats where I saw the problem.

I agree that the current approach is not end-user (us) friendly. It would help if the `conda` and `conda-build` api's didnt keep changing every month or so, but I think this is a very good time to revive and actually put some thought into moving to `conda-forge` since even the anaconda people themselves have said "yeah, use conda-forge"

**Comment by Lnaden** [comment]
The tests I ran were just forcing every single package in the repo to try and build, none of them tripped it.

**Comment by Lnaden** [comment]
I merged a workaround fix for this, let me know if it keeps having issues
