### ISSUE TITLE
MSMBuilder is loaded on the RC tag, move to main?

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/conda-recipes#736]
@rmcgibbo @mpharrigan Is there a reason we could not set the [`msmbuilder`](https://github.com/omnia-md/conda-recipes/blob/master/msmbuilder/meta.yaml#L11) package to upload as `main` instead of `rc` tag? 

We have [reports](https://github.com/omnia-md/conda-recipes/issues/702#issuecomment-285541752) of users who would [like to use it](https://github.com/msmexplorer/msmexplorer/issues/77#issuecomment-285539053) on Python 3.6, and in getting 3.6 support going, I did not realize this was uploaded under the `rc` tag so it cannot be installed without specifying that channel.

**Comment by mpharrigan** [comment]
Hi,
This is a (custom) option in the recipe. The idea is to test out the binaries before releasing them more widely. @brookehus is taking over as lead maintainer of msmbuilder. Brooke, can you move the python 3.6 packages to the main channel where appropriate?

**Comment by mpharrigan** [comment]
Historical note: this was inspired by the openmm qa procedure. Others can revisit whether it's necessary.
