### ISSUE TITLE
Update packmol

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#744]
Packmol has now made their [version history](http://leandro.iqm.unicamp.br/packmol/versionhistory/) public, and the releases have version numbers!

They even have a [GitHub repo](https://github.com/leandromartinez98/packmol/releases)!

We should update our packmol recipe to be more current, and start using a new versioning epoch that synchronizes with the official one.

@davidlmobley: Could your group help with this?

**Comment by Lnaden** [comment]
Fixed by #864
