### ISSUE TITLE
Update conda-build-all mechanism to be aware of which python versions each recipe supports

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#76]
Not all packages in `omnia` support python 3.x versions, so we will need to build some sort of infrastructure that tracks which versions of python are supported by each package and only builds these versions.

**Comment by rmcgibbo** [comment]
I'm not sure that this is actually required. Those packages just simply fail to build, and don't get deployed.

**Comment by kyleabeauchamp** [comment]
I'm going to close this--our current infrastructure seems to work fine for building and uploading any package that builds successfully.  We will revisit this when we reach omnia 1.1 and py3K support.
