### ISSUE TITLE
Has conda-forge deprecated python 3.4?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#777]
I've just noticed that recent packages on `conda-forge` don't seem to be available for python 3.4, such as [sphinx](https://anaconda.org/conda-forge/sphinx/files). If `conda-forge` has stopped building for python 3.4, we need to also disable this.

**Comment by Lnaden** [comment]
Most packages have, it really seems to be more package-specific, but I still see a few with Python 3.4 in their travis.yml files. I wonder though how many of those are just "have not made an update to since Python 3.6 was released"

**Comment by marscher** [comment]
On 05/23/2017 03:47 PM, Levi Naden wrote:
> Most packages have, it really seems to be more package-specific, but I still see a few with Python 3.4 in their travis.yml files. I wonder though how many of
> those are just "have not made an update to since Python 3.6 was released"
These have probably not rerendered their feedstocks in a long time. I have the impression that automatic rerendering PRs are not super reliable.
For example a new Python release is in the wild and the conda-smithy can handle it, there is is no automatic update for like weeks.
Of course you can always do it manually (as a feedstock maintainer).

**Comment by mpharrigan** [comment]
Even if the feedstock is re-rendered, if there isn't actually a new release of the software, it will appear as if python 3.4 is still supported because they don't delete old binaries

**Comment by Lnaden** [comment]
> don't delete old binaries

Right, thats why I was trying to base what I was seeing on the CI files like the `.travis.yml` by random clicking on a few feedstocks.

I could not find any actual documentation from the conda-forge team as to which versions they officially support anywhere though, which is why this is question is somewhat unanswered

**Comment by jchodera** [comment]
Maybe we can ask them what their policy is and where they state which versions of Python, numpy, etc. they support?

**Comment by Lnaden** [comment]
Best I can find is the [release announcement for conda 4.3](https://www.continuum.io/blog/developer-blog/anaconda-43-released) which says that 4.3 will be the last one with regular Python 3.4 support. But that is for just Anaconda's support, not conda-forge per-se

**Comment by jchodera** [comment]
Can we ask the conda-forge developers where they describe their policy about supported python versions?

**Comment by Lnaden** [comment]
Asked

**Comment by Lnaden** [comment]
Answer: Python 3.4 is no longer supported. I'll update the CI recipes in a PR and close this issue when its merged
