### ISSUE TITLE
Nothing builds on OSX Build boot-up time is so slow

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/conda-recipes#830]
See the example here from OpenMMTools 0.13.3 (#829)
https://travis-ci.org/omnia-md/conda-recipes/jobs/305290738

The time it takes to boot up the Travis worker, update Brew, install the CUDA toolkit, and install BasicTex, there is not enough time in Travis left to actually build and run anything. Splitting the jobs up over multiple tasks (e.g. #822) won't work either since each of them would have to go through the whole procedure. 

As our OSX builds are currently killed until we fix this, ideas would be good for how to fix this problem

**Comment by Lnaden** [comment]
One option: can we get rid of updating brew? Right now we uninstall `brew-cask`, untap the caskroom, then update brew, then re-install brew-cask. Based on the raw log of the linked travis log:

```
brew update -y --quiet

==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

{Downloading Stuff}

==> Pouring portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

Updated 3 taps (caskroom/cask, homebrew/core, homebrew/versions).

[34m==>[0m [1mNew Formulae[0m
```
That last line indicates to me that this step takes 34 min, which is most of our time. although I could be wrong

The Nvidia Toolkit can also be 10+ min as its download used to time out the builds until I put in #829 which changed it from a quiet download to a progress bar download with `-#` just so the terminal does not go silent. Not sure ow to fix that since we can't use Docker with Travis OSX images at the moment, and [probably won't happen](https://github.com/travis-ci/travis-ci/issues/5738#issuecomment-258961708), I can't find any additional mirrors either.

**Comment by jchodera** [comment]
We can cache the NVIDIA toolkit file in a directory. You can follow the directions [here](https://docs.travis-ci.com/user/caching/#cache-RVM-Ruby-version-for-non-Ruby-projects). That might buy us enough time.

**Comment by jchodera** [comment]
We can also add the brew cache to travis caches, which may save time in subsequent updates:
https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci

**Comment by Lnaden** [comment]
Interesting, wont that make the GitHub repo huge though?

**Comment by jchodera** [comment]
The way travis caching works is that you put a few lines in `.travis.yml` to grab a copy of the file from a local worker cache directory or, if it doesn't exist, download and stash a copy there. Travis has syntax to specify which directory to persist. It isn't guaranteed, but it will try to do so if possible.

Nothing would be added to the github repo.

**Comment by jchodera** [comment]
I did this with the old [alchemy](https://github.com/choderalab/alchemy/blob/master/.travis.yml#L16-L18) project, where the `$HOME/.cache/alchemy` would be persisted if possible and used as a place to store equilibrium simulation data for test systems that would only be simulated if the cache was not available---otherwise, the cached version would be read.

**Comment by Lnaden** [comment]
This was alleviated by #835
