### ISSUE TITLE
conda-omnia-release-osx-2 config

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#85]
This line in the configuration is not correct:
```
miniconda/bin/pip install --force-reinstall ordereddict sphinxcontrib-bibtex # needed for OpenMM
```

**Comment by jchodera** [comment]
Any idea what it should be?

**Comment by kyleabeauchamp** [comment]
We should use the conda version right?

**Comment by rmcgibbo** [comment]
Yes, conda-build should be building them. `sphinxcontrib-bibtex` is one of the packages in this repo.

**Comment by rmcgibbo** [comment]
And `ordererdict` is only required on py26, which we're (a) not building, and (b) `pip installing` it into the py27 root conda env is not going to do anything useful.

**Comment by jchodera** [comment]
OK, will just ditch this line.

**Comment by jchodera** [comment]
Done.
