### ISSUE TITLE
Debugging dependency resolution

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#86]
For the sake of debugging the dependency resolution and "unsatisfiable package requirements" type stuff, a really easy way to speed up the debugging is just to replace all of the `build.sh` scripts with a no-op, so that the packages build instaneously, but still have the same dependency structure.

```
$ cat mock-packages
#!/bin/bash
for recipe in "$@"; do
    if [ -f "$recipe/build.sh" ]; then
        echo "mocking $recipe"
        echo "echo 'building $recipe'" > $recipe/build.sh
    fi;
done
$ chmod +x mock-packages
$ mock-package ./*
```

**Comment by jchodera** [comment]
Great idea!

What about (1) adding this script to the repo, and (2) having travis run this?

**Comment by rmcgibbo** [comment]
Good idea! One sec. I've been playing with this and I have some changes to file now.
