### ISSUE TITLE
Python 3.7 and dropping 3.5

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/conda-recipes#874]
Python 3.7 is coming out in June, conda will deprecate 3.5 by the end of the year. This issue is to track what changes will be needed for it and to notify users and devs to start support.

The plan for now here will be to support Python 2.7, 3.5, 3.6 and 3.7 for several months past June, and drop 3.5 support before Conda does as well

**Comment by jchodera** [comment]
Through a bunch of pushes and PRs, I've managed to get most packages building with Python 3.7.
At this point, we should start to drop Python 3.5 and migrate to a more modern build image based on conda 4.4+ and the latest conda-forge build images. I'll open a separate issue for that.
