### ISSUE TITLE
Update travis osx build from xcode 6.4

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#928]
Travis support xcode 6.4 is [going away in Jan 2019](https://github.com/travis-ci/travis-web/pull/1759/commits) (this month!):
>  Running builds with Xcode 6.4 in Travis CI is deprecated and will be removed in January 2019. If Xcode 6.4 is critical to your builds, please contact our support team at support@travis-ci.com to discuss options.

We'll need to update our builds to use a more modern xcode.

**Comment by Lnaden** [comment]
Should we close this as a duplicate of #717 ?

**Comment by jchodera** [comment]
Thanks!
