### ISSUE TITLE
Rebuilding linux openmm

### ISSUE THREAD

**Issue by kyleabeauchamp** [omnia-md/conda-recipes#94]
So I noticed that we didn't have any openmm6.2 py3x packages (https://binstar.org/omnia/openmm/files) in the main channel, which was probably because those packages already existed in the omnia-beta channel from my previous manual builds.  I therefore deleted the manual packages and restarted the build on jenkins to see if we can get everything built by monday

**Comment by rmcgibbo** [comment]
It looks like there is a problem on https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/20/console. I think, coincident with using `--check-against omnia`, we should also have `omnia` in the `.condarc` channels. Things that are on the binstar, like `pybtex-utils` and stuff, are getting skipped during the build (as they should be), but then when things that depend on them are getting built, they're not pulled in from binstar, so they get built against.

**Comment by kyleabeauchamp** [comment]
I made that change and queued another build

**Comment by rmcgibbo** [comment]
Same thing should apply on osx https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/configure

**Comment by kyleabeauchamp** [comment]
I'll change that once I see results of linux

**Comment by jchodera** [comment]
> we should also have omnia in the .condarc channels

@rmcgibbo is totally right here.  I had removed this because I had wanted to *force* rebuild of all these packages, but with the new scheme, we should definitely have this earlier.

**Comment by jchodera** [comment]
I've made the change to `conda-omnia-release-osx-2` and restarted that build.

**Comment by kyleabeauchamp** [comment]
Still seeing some strange conda ssl issues:

```
Error: Connection error: EOF occurred in violation of protocol (_ssl.c:581): http://conda.binstar.org/omnia/linux-64/fftw3f-3.3.3-1.tar.bz2

BUILD START: openmm-6.2-py34_0

Fetching package metadata: ....
Solving package specifications: .Could not connect to http://conda.binstar.org/omnia/linux-64/fftw3f-3.3.3-1.tar.bz2
```

**Comment by rmcgibbo** [comment]
The `cvxopt` build is failing, because of `liblapack`.

```
gcc -pthread -shared build/temp.linux-x86_64-3.4/src/C/base.o build/temp.linux-x86_64-3.4/src/C/dense.o build/temp.linux-x86_64-3.4/src/C/sparse.o -L/usr/lib -L/home/vagrant/miniconda/envs/_build/lib -lm -llapack -lblas -lpython3.4m -o build/lib.linux-x86_64-3.4/cvxopt/base.cpython-34m.so
/usr/bin/ld: cannot find -llapack
collect2: ld returned 1 exit status
```

Can you `sudo apt-get install liblapack-dev` or something.

**Comment by rmcgibbo** [comment]
For some reason on linux build 21, `pybtex-docutils` got rebuilt even though its on binstar. This gives a binstar upload error at the bottom (since it exists). Not sure why.

**Comment by kyleabeauchamp** [comment]
I added this to the VM scripts here: https://github.com/omnia-md/virtual-machines/pull/19.  

@jchodera what is the best way to propagate these changes to the Jenkins machines?

**Comment by rmcgibbo** [comment]
> For some reason on linux build 21, pybtex-docutils got rebuilt even though its on binstar. This gives a binstar upload error at the bottom (since it exists). Not sure why.

I can reproduce this locally -- debugging now.

**Comment by jchodera** [comment]
> @jchodera what is the best way to propagate these changes to the Jenkins machines?

I've changed the `conda-omnia-release-linux-vagrant` recipe so that it no longer tries to reinitialize the VM but instead rebuilds inside the VM when `omnia-md/conda-recipes` is updated.

I think at this point, we should have the [`rebuild-omnia-virtual-machines`](https://jenkins.choderalab.org/job/rebuild-omnia-virtual-machines/) project provision a new vagrant box from [`omnia-md/virtual-machines`](https://github.com/omnia-md/virtual-machines) and package up a new vagrant box locally.  Then we would change the jenkins `conda-omnia-release-linux-vagrant` project to reprovision a fresh vagrant box every time from this packaged box, only updating `conda`, but this should be very quick.  It will take a couple hours of tinkering to get this to work, though.

What do you think?

**Comment by rmcgibbo** [comment]
Another option is to put `sudo yum install -y lapack-devel` at the top of the `conda-omnia-release-linux-vagrant` config script, and sort this out later. :)

**Comment by rmcgibbo** [comment]
Oh. Lol. The reason that `pybtex-docutils` gets rebuilt is because it has a `'-'` in the name, and `conda-build-all` has a bug. Will file PR soon.

**Comment by kyleabeauchamp** [comment]
Let's just monkeypatch the extra yum packages for now--we should avoid rebuilding the machines because there's a very real possibility of texlive repos going down.

**Comment by jchodera** [comment]
`sudo yum install -y lapack-devel` it is!  Let me do this now.

**Comment by jchodera** [comment]
Monkey patch in place!  Rebuilding.

**Comment by rmcgibbo** [comment]
you should merge #95 first, and kill two birds w/ one stone.

**Comment by jchodera** [comment]
Done.

**Comment by kyleabeauchamp** [comment]
Hmm, some strange swig stuff going down here:

```
src/swig_doxygen/OpenMMSwig.cxx:2521: error: ‚ÄòPyCObject_FromVoidPtr‚Äô was not declared in this scope
src/swig_doxygen/OpenMMSwig.cxx:2512: warning: unused variable ‚Äòswig_empty_runtime_method_table‚Äô
src/swig_doxygen/OpenMMSwig.cxx: In function ‚Äòswig_type_info* SWIG_Python_TypeQuery(const char*)‚Äô:
src/swig_doxygen/OpenMMSwig.cxx:2544: error: ‚ÄòPyCObject_AsVoidPtr‚Äô was not declared in this scope
src/swig_doxygen/OpenMMSwig.cxx:2549: error: ‚ÄòPyCObject_FromVoidPtr‚Äô was not declared in this scope
src/swig_doxygen/OpenMMSwig.cxx: In function ‚Äòstd::vector<double, std::allocator<double> >* std_vector_Sl_double_Sg____getitem____SWIG_0(std::vector<double, std::allocator<double> >*, PySliceObject*)‚Äô:
src/swig_doxygen/OpenMMSwig.cxx:4885: error: cannot convert ‚ÄòP

[...]

error: command 'gcc' failed with exit status 1

[...]

Command failed: /bin/bash -x -e /home/vagrant/conda-recipes/openmm/build.sh
```

**Comment by jchodera** [comment]
Which Python version is having trouble?

**Comment by kyleabeauchamp** [comment]
Looks like both 3.3 and 3.4

**Comment by kyleabeauchamp** [comment]
So on my local VM, the command `conda-build-all openmm` seems to work fine:

```
BUILD END: openmm-6.2-py34_0
Nothing to test for: openmm-6.2-py34_0
# If you want to upload this package to binstar.org later, type:
#
# $ binstar upload /home/vagrant/miniconda/conda-bld/linux-64/openmm-6.2-py34_0.tar.bz2
#
# To have conda build upload to binstar automatically, use
# $ conda config --set binstar_upload yes
```

**Comment by jchodera** [comment]
Any ideas how to proceed here?

**Comment by rmcgibbo** [comment]
I have no idea what's going on with the weird characters. I've never seen anything like that.

**Comment by kyleabeauchamp** [comment]
There's also some other strangeness here, but I think that's possibly a red herring.  Again, I can't reproduce this with a straight-up `conda-build openmmtools` on my VM

```

Installed /home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/openmmtools-0.9.0-py2.7.egg
Processing dependencies for openmmtools==0.9.0
Searching for nose
Traceback (most recent call last):
  File "setup.py", line 177, in <module>
    ext_modules=extensions,
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/command/install.py", line 67, in run
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/command/easy_install.py", line 376, in run
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/command/easy_install.py", line 600, in easy_install
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/command/easy_install.py", line 651, in install_item
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/command/easy_install.py", line 699, in process_distribution
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 797, in resolve
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 1047, in best_match
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 1059, in obtain
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/command/easy_install.py", line 607, in easy_install
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/package_index.py", line 595, in fetch_distribution
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/package_index.py", line 432, in find_packages
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/package_index.py", line 766, in scan_url
  File "/home/vagrant/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/package_index.py", line 284, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/nose/r
```

**Comment by jchodera** [comment]
The same VM has been used over and over, so it's possible that it just needs to be rebuilt.

**Comment by rmcgibbo** [comment]
We still haven't produced the linux-64 py3 build of OpenMM.

**Comment by rmcgibbo** [comment]
@kyleabeauchamp: if you can produce a proper OpenMM linux-64 py3 build from the recipe, including the GPU libraries, IMO you should push that copy onto binstar. We can solve the swig issue later.

**Comment by kyleabeauchamp** [comment]
Done, but need testing

**Comment by rmcgibbo** [comment]
I downloaded the py34 and installed. Files look good. All the GPU libraries are there.

```
$ python -m simtk.testInstallation
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 2.02073e-05
Reference vs. OpenCL: 2.15539e-05
CPU vs. OpenCL: 1.5909e-05
```
The fact that CUDA isn't there is my fault -- not yours.

```
(3.4)rmcgibbo@vspm9  ~ (3.4)
$ ldd ~/miniconda/envs/3.4/lib/plugins/libOpenMMCUDA.so
	linux-vdso.so.1 =>  (0x00007fffa407c000)
	libOpenMM.so => /home/rmcgibbo/miniconda/envs/3.4/lib/plugins/../libOpenMM.so (0x00007fefcb96c000)
	libcuda.so.1 => /usr/lib/libcuda.so.1 (0x00007fefca9d8000)
	libcufft.so.6.5 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fefca7b9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fefca5b5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fefca2b1000)
	libm.so.6 => /home/rmcgibbo/miniconda/envs/3.4/lib/plugins/../libm.so.6 (0x00007fefca02d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fefc9e17000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fefc9a51000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fefc9848000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fefc962f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fefcc27e000)
```
I don't have CUDA 6.5 installed (I think I have 6.0), so this is expected.

**Comment by rmcgibbo** [comment]
The thing with `sphinx` and `sphinxcontib-bibtex` being included is still there, but that's separate.

**Comment by kyleabeauchamp** [comment]
I rebuilt with the updated conda recipe and uploaded the py33 and py34 to binstar.  the py27 was working from jenkins, which I still don't quite understand
